import debate
import gleam/int
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import senators
import session
import theme

const max_turns = 10

pub fn render_session_page(
  sess: session.Session,
  senators_list: List(senators.Senator),
  autopilot_running: Bool,
  current_theme: theme.Theme,
) -> String {
  let bill_section = render_bill(sess.bill)
  let debate_section = render_debate_log(sess)
  let amendment_section = render_amendments(sess.amendments)
  let roster_section = render_roster(sess, senators_list)
  let error_section = render_error_banner(sess.last_error)
  let status_line = render_status_line(sess)
  let autopilot_controls =
    render_autopilot_controls(sess, autopilot_running, current_theme)
  let nav_links = render_nav_links(current_theme)
  let theme_switcher = render_theme_switcher(current_theme, "/")
  let body_class = theme.body_class(current_theme)
  let refresh_script = live_update_script()

  "<!doctype html>
   <html lang=\"en\">
     <head>
       <meta charset=\"utf-8\" />
       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
       <title>Harmony Chamber</title>
       <style>" <> stylesheet() <> "</style>
     </head>
     <body class=\"" <> body_class <> "\">
      <div class=\"page\">
        <header class=\"hero\" id=\"hero-header\">
          <div>
             <p class=\"eyebrow\">Harmony Chamber</p>
             <h1>Multi-Agent Senate Simulation</h1>
             <nav class=\"nav-links\">
               " <> nav_links <> "
             </nav>
            <p class=\"hero-summary\">
              Live session generated by Gleam/BEAM + OpenAI agents.
            </p>
             <p>
               LLM calls used: " <> int.to_string(sess.llm_calls_used) <> " / " <> int.to_string(
    sess.llm_calls_limit,
  ) <> "
             </p>
             " <> status_line <> "
             " <> autopilot_controls <> "
             " <> theme_switcher <> "
           </div>
         </header>
        " <> error_section <> "
        <main class=\"grid\">
          " <> bill_section <> "
          " <> debate_section <> "
          " <> amendment_section <> "
         </main>
         " <> roster_section <> "
       </div>
     " <> refresh_script <> "
     </body>
   </html>"
}

pub fn render_docket_page(
  current: session.Bill,
  completed: List(session.CompletedBill),
  upcoming: List(session.Bill),
  current_theme: theme.Theme,
) -> String {
  let completed_section = render_completed_bills(completed)
  let upcoming_section = render_upcoming_bills(current, upcoming)
  let nav_links = render_nav_links(current_theme)
  let theme_switcher = render_theme_switcher(current_theme, "/docket")
  let body_class = theme.body_class(current_theme)

  "<!doctype html>
   <html lang=\"en\">
     <head>
       <meta charset=\"utf-8\" />
       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
       <title>Harmony Chamber Docket</title>
       <style>" <> stylesheet() <> "</style>
     </head>
     <body class=\"" <> body_class <> "\">
       <div class=\"page\">
         <header class=\"hero\">
           <div>
             <p class=\"eyebrow\">Harmony Chamber</p>
             <h1>Legislative Docket</h1>
             <nav class=\"nav-links\">
               " <> nav_links <> "
             </nav>
             <p class=\"hero-summary\">
               Completed votes and upcoming legislation.
             </p>
             " <> theme_switcher <> "
           </div>
         </header>
         <main class=\"grid\">
           " <> completed_section <> "
           " <> upcoming_section <> "
         </main>
       </div>
     </body>
   </html>"
}

pub fn render_history_page(
  completed: List(session.CompletedBill),
  current_theme: theme.Theme,
) -> String {
  let body = case completed {
    [] -> "<p>No completed votes yet.</p>"
    _ ->
      completed
      |> list.map(render_history_card)
      |> string.join("")
  }
  let nav_links = render_nav_links(current_theme)
  let theme_switcher = render_theme_switcher(current_theme, "/history")
  let body_class = theme.body_class(current_theme)

  "<!doctype html>
   <html lang=\"en\">
     <head>
       <meta charset=\"utf-8\" />
       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
       <title>Harmony Chamber Vote History</title>
       <style>" <> stylesheet() <> "</style>
     </head>
     <body class=\"" <> body_class <> "\">
       <div class=\"page\">
         <header class=\"hero\">
           <div>
             <p class=\"eyebrow\">Harmony Chamber</p>
             <h1>Vote History</h1>
             <nav class=\"nav-links\">
               " <> nav_links <> "
             </nav>
             <p class=\"hero-summary\">
               Full record of completed bills, amendments, and transcripts.
             </p>
             " <> theme_switcher <> "
           </div>
         </header>
         <section class=\"panel docket-panel\">
           <div class=\"panel-header\">
             <h2>Completed votes</h2>
             <p>Includes raw debate text for archival access.</p>
           </div>
           <div class=\"docket-list\">" <> body <> "</div>
         </section>
       </div>
     </body>
   </html>"
}

fn render_bill(bill: session.Bill) -> String {
  "<section class=\"panel bill-panel\" id=\"bill-panel\">
     <div class=\"panel-header\">
       <h2>" <> escape_html(bill.title) <> "</h2>
       <p class=\"bill-id\">Bill " <> escape_html(bill.id) <> "</p>
     </div>
     <p class=\"bill-summary\">" <> escape_html(bill.summary) <> "</p>
   </section>"
}

fn render_debate_log(sess: session.Session) -> String {
  let turns =
    sess.debate_turns
    |> list.reverse
    |> list.take(max_turns)
    |> list.reverse

  let body = case turns {
    [] ->
      "<div class=\"empty-transcript\">
         <p>No speeches logged yet. Senators are still reviewing the bill.</p>
       </div>"
    _ ->
      turns
      |> list.map(render_turn_card)
      |> string.join("")
  }

  "<section class=\"panel transcript-panel\" id=\"debate-panel\">
     <div class=\"panel-header\">
       <h2>Debate Floor</h2>
       <p>The most recent " <> int.to_string(max_turns) <> " turns appear below.</p>
     </div>
     <div class=\"transcript-grid\">" <> body <> "</div>
   </section>"
}

fn render_turn_card(turn: debate.DebateTurn) -> String {
  let senator_link = senator_inline_link(turn.senator)

  "<article class=\"turn-card\">
     <div class=\"turn-meta\">
       <span class=\"turn-index\">Turn #" <> int.to_string(turn.turn_index) <> "</span>
       <span class=\"turn-senator\">" <> senator_link <> "</span>
       <span class=\"turn-vote\">" <> escape_html(debate.vote_intent_label(
    turn.vote_intent,
  )) <> "</span>
     </div>
     " <> render_turn_tags(turn) <> "
     <div class=\"turn-text\">" <> format_speech(turn.speech) <> "</div>
   </article>"
}

fn render_turn_tags(turn: debate.DebateTurn) -> String {
  let purpose = string.trim(turn.purpose)

  let purpose_tag =
    case purpose {
      "" -> ""
      _ -> "<span class=\"pill tag\">Purpose: " <> escape_html(purpose) <> "</span>"
    }

  let procedure_tag =
    case turn.procedure {
      debate.NoProcedure -> ""
      _ ->
        "<span class=\"pill tag\">Procedure: " <> escape_html(
          debate.procedure_label(turn.procedure),
        ) <> "</span>"
    }

  let tags =
    [purpose_tag, procedure_tag]
    |> list.filter(fn(tag) { tag != "" })
    |> string.join("")

  case tags {
    "" -> ""
    _ -> "<div class=\"turn-tags\">" <> tags <> "</div>"
  }
}

fn render_amendments(amendments: List(session.Amendment)) -> String {
  let content = case amendments {
    [] ->
      "<div class=\"empty-transcript\">
         <p>No amendments proposed yet. Senators may submit a full replacement text.</p>
       </div>"
    _ ->
      amendments
      |> list.map(render_amendment_card)
      |> string.join("")
  }

  "<section class=\"panel amendment-panel\" id=\"amendment-panel\">
     <div class=\"panel-header\">
       <h2>Amendments</h2>
       <p>Each amendment replaces the bill text if adopted.</p>
     </div>
     <div class=\"amendment-list\">" <> content <> "</div>
   </section>"
}

fn render_amendment_card(amendment: session.Amendment) -> String {
  let vote_summary = case amendment.vote_result {
    None -> ""
    Some(result) ->
      "<p class=\"amendment-vote\">Vote: " <> escape_html(
        format_result_summary(result),
      ) <> "</p>"
  }

  "<article class=\"card amendment-card\">
     <div class=\"amendment-meta\">
       <h3>Amendment " <> int.to_string(amendment.id) <> "</h3>
       <p>Proposed by " <> senator_inline_link(amendment.proposer) <> "</p>
       <p>Status: " <> escape_html(format_amendment_status(amendment.status)) <> "</p>
       " <> vote_summary <> "
     </div>
     <div class=\"amendment-text\">" <> format_speech(amendment.text) <> "</div>
   </article>"
}

fn render_roster(
  sess: session.Session,
  senators_list: List(senators.Senator),
) -> String {
  let cards =
    senators_list
    |> list.map(fn(senator) {
      let anchor_id = senator_anchor_id(senator)
      let intent = case session.vote_intent_for(sess, senator.id) {
        Some(value) -> value
        None -> debate.Undecided
      }

      "<article class=\"card senator-card\" id=\"" <> anchor_id <> "\">
         <h3>" <> escape_html(senator.name) <> "</h3>
         <p class=\"senator-meta\">" <> escape_html(senator.state) <> " &middot; Vote intent: " <> escape_html(
        debate.vote_intent_label(intent),
      ) <> "</p>
         <p class=\"senator-bio\">" <> escape_html(biography_snippet(
        senator.biography,
      )) <> "</p>
       </article>"
    })
    |> string.join("")

  "<section class=\"panel senator-panel\" id=\"senator-panel\">
     <div class=\"panel-header\">
       <h2>Senatorial Ledger</h2>
       <p>Background summaries and current vote intentions.</p>
     </div>
     <div class=\"senator-grid\">" <> cards <> "</div>
   </section>"
}

fn render_error_banner(error: Option(String)) -> String {
  let content = case error {
    None -> ""
    Some(message) -> "<div class=\"alert\">
         <p>LLM decision error: " <> escape_html(message) <> "</p>
       </div>"
  }

  "<div id=\"alert-banner\">" <> content <> "</div>"
}

fn render_status_line(sess: session.Session) -> String {
  let label = status_label(sess.status)

  let result_text =
    case sess.final_result {
      None -> ""
      Some(result) -> "Result: " <> format_result_summary(result)
    }

  let note =
    case sess.status {
      session.Closed ->
        "Deliberations closed. No further LLM calls will be made for this bill."
      session.Voting(session.BillVote) ->
        "Voting on the bill text is in progress. Tallies will finalize shortly."
      session.Voting(session.AmendmentVote(id)) ->
        "Voting on amendment " <> int.to_string(id) <> " is underway."
      session.InDebate ->
        "Debate in progress. Senators speak selectively with purpose."
    }

  let details =
    [result_text, note]
    |> list.filter(fn(text) { string.trim(text) != "" })
    |> list.map(escape_html)
    |> string.join(" · ")

  "<p class=\"status-line\"><span class=\"pill status-pill\">"
    <> escape_html(label)
    <> "</span> <span class=\"status-detail\">"
    <> details
    <> "</span></p>"
}

fn status_label(status: session.SessionStatus) -> String {
  case status {
    session.InDebate -> "In debate"
    session.Voting(session.BillVote) -> "Voting on bill"
    session.Voting(session.AmendmentVote(id)) ->
      "Voting on amendment " <> int.to_string(id)
    session.Closed -> "Closed"
  }
}

fn render_nav_links(current_theme: theme.Theme) -> String {
  [
    nav_link("/", "Current session", current_theme),
    nav_link("/docket", "Bill docket", current_theme),
    nav_link("/history", "Vote history", current_theme),
  ]
  |> string.join("")
}

fn nav_link(path: String, label: String, current_theme: theme.Theme) -> String {
  "<a href=\""
    <> path
    <> theme.query_suffix(current_theme)
    <> "\">"
    <> label
    <> "</a>"
}

fn render_theme_switcher(
  current_theme: theme.Theme,
  base_path: String,
) -> String {
  let buttons =
    theme.available()
    |> list.map(fn(option) {
      let active = option == current_theme
      let href =
        case theme.query_suffix(option) {
          "" -> base_path
          suffix -> base_path <> suffix
        }

      "<a class=\"" <> theme_button_class(active) <> "\" href=\"" <> href <> "\">" <> theme.label(
        option,
      ) <> "</a>"
    })
    |> string.join("")

  "<div class=\"theme-switcher\">
     <span class=\"theme-label\">Theme:</span>
     " <> buttons <> "
   </div>"
}

fn theme_button_class(active: Bool) -> String {
  case active {
    True -> "theme-button is-active"
    False -> "theme-button"
  }
}

fn senator_inline_link(senator: senators.Senator) -> String {
  let href = senator_anchor_href(senator)
  let label =
    escape_html(senator.name)
      <> " ("
      <> escape_html(senator.state)
      <> ")"

  "<a class=\"senator-link\" href=\"" <> href <> "\">" <> label <> "</a>"
}

fn senator_anchor_href(senator: senators.Senator) -> String {
  "#" <> senator_anchor_id(senator)
}

fn senator_anchor_id(senator: senators.Senator) -> String {
  "senator-" <> clean_anchor_fragment(senator.id)
}

fn clean_anchor_fragment(raw: String) -> String {
  raw
  |> string.to_utf_codepoints
  |> list.fold("", fn(acc, cp) {
    let value = string.utf_codepoint_to_int(cp)
    case is_anchor_char(value) {
      True -> acc <> string.from_utf_codepoints([cp])
      False -> acc <> "-"
    }
  })
}

fn is_anchor_char(code: Int) -> Bool {
  code >= 48 && code <= 57
    || code >= 65 && code <= 90
    || code >= 97 && code <= 122
    || code == 45
    || code == 95
}

fn render_autopilot_controls(
  sess: session.Session,
  running: Bool,
  current_theme: theme.Theme,
) -> String {
  let #(action, label, note) = case running {
    True ->
      #(
        "pause",
        "Pause Simulation",
        "Simulation is advancing automatically. Pause if you need a moment to review.",
      )
    False -> {
      let started = session_has_started(sess)
      #(
        "resume",
        case started {
          True -> "Resume Simulation"
          False -> "Start Simulation"
        },
        case started {
          True -> "Simulation paused — resume when you're ready for more turns."
          False -> "Simulation is staged. Start it to generate the first speeches."
        },
      )
    }
  }
  let suffix = theme.query_suffix(current_theme)

  "<div class=\"control-bar\" id=\"autopilot-controls\">
     <form action=\"/autopilot/" <> action <> suffix <> "\" method=\"post\">
       <button class=\"pill-button\" type=\"submit\">" <> label <> "</button>
     </form>
     <p class=\"autopilot-note\">" <> note <> "</p>
   </div>"
}

fn session_has_started(sess: session.Session) -> Bool {
  sess.debate_turns != [] || sess.llm_calls_used > 0
}

fn live_update_script() -> String {
  "<script>
     const harmonyUpdateTargets = [
       \"#hero-header\",
       \"#bill-panel\",
       \"#debate-panel\",
       \"#amendment-panel\",
       \"#senator-panel\",
       \"#alert-banner\"
     ];

     async function harmonyRefreshPanels() {
       if (document.hidden) return;
       try {
         const response = await fetch(window.location.href, { headers: { \"X-Harmony-Refresh\": \"1\" } });
         if (!response.ok) return;
         const text = await response.text();
         const parser = new DOMParser();
         const doc = parser.parseFromString(text, \"text/html\");
         harmonyUpdateTargets.forEach((selector) => {
           const next = doc.querySelector(selector);
           const current = document.querySelector(selector);
           if (next && current) {
             current.innerHTML = next.innerHTML;
           }
         });
       } catch (_error) {
         // Ignore transient network issues
       }
     }

     setInterval(harmonyRefreshPanels, 8000);
   </script>"
}

fn format_amendment_status(status: session.AmendmentStatus) -> String {
  case status {
    session.Pending -> "Pending"
    session.Adopted -> "Adopted"
    session.Rejected -> "Rejected"
  }
}

fn render_completed_bills(
  bills: List(session.CompletedBill),
) -> String {
  let body = case bills {
    [] ->
      "<p>No completed votes yet. The first bill is still in progress.</p>"
    _ ->
      bills
      |> list.map(render_completed_card)
      |> string.join("")
  }

  "<section class=\"panel docket-panel\">
     <div class=\"panel-header\">
       <h2>Completed Legislation</h2>
       <p>Vote totals for every bill and amendment finished so far.</p>
     </div>
     <div class=\"docket-list\">" <> body <> "</div>
   </section>"
}

fn render_completed_card(record: session.CompletedBill) -> String {
  let summary =
    case record.result {
      None -> "Awaiting final vote"
      Some(result) -> format_result_summary(result)
    }

  let amendment_list = render_amendment_history(record.amendments)

  "<article class=\"card amendment-card\">
     <h3>" <> escape_html(record.bill.title) <> "</h3>
     <p class=\"amendment-vote\">Final vote: " <> escape_html(summary) <> "</p>
     <div class=\"amendment-text\">
       <h4>Amendments</h4>
       " <> amendment_list <> "
     </div>
   </article>"
}

fn render_history_card(record: session.CompletedBill) -> String {
  let summary =
    case record.result {
      None -> "No final vote recorded"
      Some(result) -> format_result_summary(result)
    }

  let amendment_list = render_amendment_history(record.amendments)

  "<article class=\"card amendment-card\">
     <h3>" <> escape_html(record.bill.title) <> "</h3>
     <p class=\"amendment-vote\">Final vote: " <> escape_html(summary) <> "</p>
     <div class=\"amendment-text\">
       <h4>Amendments</h4>
       " <> amendment_list <> "
     </div>
     <details class=\"transcript-block\">
       <summary>View full debate transcript</summary>
       <pre>" <> escape_html(record.transcript_text) <> "</pre>
     </div>
   </article>"
}

fn render_amendment_history(amendments: List(session.Amendment)) -> String {
  case amendments {
    [] -> "<p>No amendments were proposed.</p>"
    _ ->
      amendments
      |> list.map(fn(amendment) {
        "<li><strong>" <> senator_inline_link(amendment.proposer) <> "</strong>: "
          <> escape_html(format_amendment_status(amendment.status))
          <> case amendment.vote_result {
            None -> ""
            Some(result) -> " — " <> escape_html(format_result_summary(result))
          }
          <> "</li>"
      })
      |> string.join("")
      |> fn(items) { "<ul>" <> items <> "</ul>" }
  }
}

fn render_upcoming_bills(
  current: session.Bill,
  upcoming: List(session.Bill),
) -> String {
  let upcoming_cards =
    upcoming
    |> list.map(fn(bill) {
      "<article class=\"card senator-card\">
         <h3>" <> escape_html(bill.title) <> "</h3>
         <p class=\"bill-id\">Bill " <> escape_html(bill.id) <> "</p>
         <p>" <> escape_html(bill.summary) <> "</p>
       </article>"
    })
    |> string.join("")

  "<section class=\"panel bill-panel\">
     <div class=\"panel-header\">
       <h2>On Deck</h2>
       <p>Currently debating: " <> escape_html(current.title) <> "</p>
     </div>
     <div class=\"senator-grid\">" <> upcoming_cards <> "</div>
   </section>"
}

fn format_result_summary(result: session.VoteResult) -> String {
  let session.VoteResult(tally: tally, passed: passed) = result
  let session.VoteTally(yea: yea, nay: nay, abstain: abstain) = tally
  let verdict = case passed {
    True -> "Passed"
    False -> "Failed"
  }

  let abstain_suffix = case abstain > 0 {
    True -> " (" <> int.to_string(abstain) <> " abstaining)"
    False -> ""
  }

  verdict
    <> " "
    <> int.to_string(yea)
    <> "-"
    <> int.to_string(nay)
    <> abstain_suffix
}

fn biography_snippet(bio: String) -> String {
  let paragraphs = string.split(bio, "\n\n")
  let snippet = case paragraphs {
    [] -> bio
    [first, ..] -> first
  }

  case string.length(snippet) > 280 {
    True -> string.slice(snippet, 0, 277) <> "..."
    False -> snippet
  }
}

fn format_speech(text: String) -> String {
  case string.trim(text) {
    "" -> "<p>(No speech recorded this turn.)</p>"
    cleaned ->
      cleaned
      |> string.split("\n\n")
      |> list.map(fn(paragraph) { "<p>" <> escape_html(paragraph) <> "</p>" })
      |> string.join("")
  }
}

fn escape_html(text: String) -> String {
  text
  |> string.replace("&", "&amp;")
  |> string.replace("<", "&lt;")
  |> string.replace(">", "&gt;")
  |> string.replace("\"", "&quot;")
  |> string.replace("'", "&#39;")
}

fn stylesheet() -> String {
  "
  :root {
    --parchment: #f3efe2;
    --ink: #2d2a24;
    --accent: #c1a364;
    --shadow: rgba(0, 0, 0, 0.08);
  }

  * { box-sizing: border-box; }

  body {
    margin: 0;
    font-family: 'Georgia', 'Garamond', serif;
    background: var(--parchment);
    color: var(--ink);
  }

  .page {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem 1.5rem 4rem;
  }

  .hero {
    background: #f9f5ea;
    border: 2px solid var(--accent);
    border-radius: 1rem;
    padding: 1.5rem 2rem;
    box-shadow: 0 10px 30px var(--shadow);
    margin-bottom: 1.5rem;
  }

  .eyebrow {
    text-transform: uppercase;
    letter-spacing: 0.2em;
    font-size: 0.8rem;
    margin: 0 0 0.4rem;
    color: #8c6a2f;
  }

  .hero-summary {
    margin: 0.4rem 0 0;
    max-width: 40rem;
  }

  .nav-links {
    display: flex;
    gap: 0.75rem;
    margin: 0.5rem 0 0.5rem;
    font-size: 0.9rem;
  }

  .nav-links a {
    color: #2d2a24;
    text-decoration: none;
    border-bottom: 1px solid transparent;
    padding-bottom: 0.1rem;
  }

  .nav-links a:hover {
    border-color: #2d2a24;
  }

  .senator-link {
    color: inherit;
    text-decoration: underline dotted;
    transition: color 0.15s ease;
  }

  .senator-link:hover {
    text-decoration: underline;
  }

  .status-line {
    margin: 0.5rem 0 0;
    font-weight: 600;
    color: #5a4a30;
  }

  .status-detail {
    font-weight: 400;
    margin-left: 0.5rem;
  }

  .pill {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
    padding: 0.25rem 0.75rem;
    border-radius: 999px;
    background: #e8dcc0;
    border: 1px solid #c1a364;
    font-size: 0.85rem;
    letter-spacing: 0.02em;
  }

  .status-pill {
    background: #d9c28d;
  }

  .control-bar {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
    align-items: center;
    margin-top: 0.75rem;
  }

  .theme-switcher {
    margin-top: 0.75rem;
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    align-items: center;
  }

  .theme-label {
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.18em;
    color: #6b5634;
  }

  .theme-button {
    text-decoration: none;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    border: 1px solid #c1a364;
    padding: 0.2rem 0.6rem;
    border-radius: 0.6rem;
    color: #2d2a24;
    background: rgba(255, 255, 255, 0.6);
    transition: background 0.2s ease, color 0.2s ease;
  }

  .theme-button.is-active {
    background: #2d2a24;
    color: #fff;
  }

  .pill-button {
    border: none;
    background: #2d2a24;
    color: #fff;
    padding: 0.45rem 1.1rem;
    border-radius: 999px;
    font-size: 0.9rem;
    cursor: pointer;
    transition: opacity 0.15s ease;
  }

  .pill-button:hover {
    opacity: 0.85;
  }

  .autopilot-note {
    margin: 0;
    color: #5a4a30;
    font-size: 0.9rem;
  }

  .alert {
    background: #fff2e4;
    border: 1px solid #d27c35;
    border-radius: 0.5rem;
    padding: 0.75rem 1rem;
    margin-bottom: 1rem;
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 1.5rem;
    margin-bottom: 2rem;
  }

  .panel {
    background: #fffdf8;
    border: 2px solid #dac6a3;
    border-radius: 1rem;
    padding: 1.5rem;
    box-shadow: 0 8px 24px var(--shadow);
  }

  .panel-header h2 {
    margin: 0;
    font-size: 1.4rem;
  }

  .panel-header p {
    margin: 0.3rem 0 0;
    color: #5a4a30;
  }

  .bill-summary {
    line-height: 1.6;
  }

  .transcript-grid {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .turn-card {
    background: #fffaf0;
    border: 1px solid rgba(151, 121, 70, 0.4);
    border-radius: 0.75rem;
    padding: 1rem;
    box-shadow: 0 6px 20px var(--shadow);
  }

  .turn-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem 1rem;
    font-size: 0.9rem;
    margin-bottom: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #6f5632;
  }

  .turn-text p {
    margin: 0 0 0.6rem;
    line-height: 1.55;
  }

  .turn-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 0.4rem;
    margin: 0 0 0.5rem;
  }

  .tag {
    background: #f1e6d0;
  }

  .empty-transcript {
    border: 1px dashed #c5ab78;
    border-radius: 0.75rem;
    padding: 1rem;
    font-style: italic;
    color: #6b5a37;
  }

  .senator-panel {
    margin-top: 2rem;
  }

  .senator-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 1rem;
    margin-top: 1rem;
  }

  .card {
    background: #fffef9;
    border: 1px solid rgba(149, 115, 60, 0.35);
    border-radius: 0.75rem;
    padding: 1rem;
    box-shadow: 0 4px 16px var(--shadow);
  }

  .senator-card h3 {
    margin: 0;
  }

  .senator-meta {
    margin: 0.35rem 0;
    font-size: 0.95rem;
    color: #6a5533;
  }

  .senator-bio {
    margin: 0;
    line-height: 1.4;
  }

  .amendment-panel .amendment-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin-top: 1rem;
  }

  .amendment-card h3 {
    margin: 0 0 0.25rem 0;
  }

  .amendment-meta p {
    margin: 0.1rem 0;
    font-size: 0.9rem;
    color: #5b4a33;
  }

  .amendment-text {
    margin-top: 0.5rem;
  }

  .amendment-text p {
    margin: 0 0 0.6rem;
  }

  .amendment-vote {
    font-weight: 600;
  }

  .docket-panel .docket-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin-top: 1rem;
  }

  .transcript-block {
    margin-top: 0.75rem;
  }

  .transcript-block pre {
    background: #f4efe0;
    padding: 0.75rem;
    border-radius: 0.5rem;
    white-space: pre-wrap;
    max-height: 20rem;
    overflow-y: auto;
  }

  body.theme-terminal {
    background-color: #020b04;
    color: #d4ffe0;
    font-family: 'Share Tech Mono', 'IBM Plex Mono', 'SFMono-Regular', 'Liberation Mono', monospace;
    text-shadow: 0 0 8px rgba(13, 244, 106, 0.18);
    background-image:
      radial-gradient(circle at 15% 20%, rgba(13, 244, 106, 0.12), transparent 45%),
      repeating-linear-gradient(0deg, rgba(13, 244, 106, 0.04) 0px, rgba(13, 244, 106, 0.04) 1px, transparent 1px, transparent 4px);
    background-attachment: fixed;
  }

  body.theme-terminal .page {
    background: rgba(0, 0, 0, 0.55);
  }

  body.theme-terminal .hero {
    background: rgba(3, 18, 11, 0.95);
    border-color: #0df46a;
    box-shadow: 0 0 35px rgba(13, 244, 106, 0.35);
  }

  body.theme-terminal .nav-links a {
    color: #9ffec9;
    border-color: rgba(13, 244, 106, 0.25);
  }

  body.theme-terminal .nav-links a:hover {
    border-color: #9ffec9;
  }

  body.theme-terminal .hero-summary,
  body.theme-terminal .status-line,
  body.theme-terminal .status-detail,
  body.theme-terminal .theme-label,
  body.theme-terminal .autopilot-note,
  body.theme-terminal .panel-header p,
  body.theme-terminal .senator-meta,
  body.theme-terminal .amendment-meta p {
    color: #9bf7c9;
  }

  body.theme-terminal .pill,
  body.theme-terminal .tag {
    background: rgba(13, 244, 106, 0.12);
    border-color: rgba(13, 244, 106, 0.45);
    color: #adffd8;
  }

  body.theme-terminal .status-pill {
    background: rgba(13, 244, 106, 0.3);
    color: #012812;
  }

  body.theme-terminal .control-bar {
    border-top: 1px solid rgba(13, 244, 106, 0.2);
    padding-top: 0.75rem;
  }

  body.theme-terminal .theme-button {
    border-color: rgba(13, 244, 106, 0.5);
    color: #96fccc;
    background: rgba(2, 26, 16, 0.9);
  }

  body.theme-terminal .theme-button.is-active {
    background: #0df46a;
    color: #022011;
  }

  body.theme-terminal .pill-button {
    background: #0df46a;
    color: #031910;
    box-shadow: 0 0 25px rgba(13, 244, 106, 0.45);
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  body.theme-terminal .pill-button:hover {
    opacity: 1;
    filter: brightness(1.1);
  }

  body.theme-terminal .panel,
  body.theme-terminal .card,
  body.theme-terminal .turn-card,
  body.theme-terminal .amendment-card {
    background: rgba(2, 20, 12, 0.95);
    border-color: rgba(13, 244, 106, 0.35);
    box-shadow: 0 0 30px rgba(0, 0, 0, 0.75);
    color: #d6ffd7;
  }

  body.theme-terminal .turn-meta {
    color: #8ef7ba;
  }

  body.theme-terminal .empty-transcript {
    border-color: rgba(13, 244, 106, 0.35);
    color: #a4ffd3;
    background: rgba(2, 26, 14, 0.8);
  }

  body.theme-terminal .alert {
    background: rgba(255, 102, 102, 0.08);
    border-color: #ff7b7b;
    color: #ffc0c0;
  }

  body.theme-terminal .transcript-block pre {
    background: #04170c;
    color: #befed9;
  }

  body.theme-terminal .senator-bio,
  body.theme-terminal .bill-summary,
  body.theme-terminal .amendment-text,
  body.theme-terminal .turn-text p {
    color: #e1ffe6;
  }

  body.theme-terminal .theme-switcher {
    border-top: 1px solid rgba(13, 244, 106, 0.2);
    padding-top: 0.75rem;
  }

  body.theme-terminal .theme-button.is-active,
  body.theme-terminal .pill-button {
    text-shadow: none;
  }

  body.theme-blossom {
    background: radial-gradient(circle at 20% 20%, #ffe9f4, #ffd2ec, #ffc3e5);
    color: #5d1a3d;
    font-family: 'Baloo 2', 'Nunito', 'Trebuchet MS', sans-serif;
  }

  body.theme-blossom .hero {
    background: rgba(255, 255, 255, 0.85);
    border-color: #ff9bcf;
    box-shadow: 0 15px 35px rgba(255, 155, 207, 0.4);
  }

  body.theme-blossom .nav-links a {
    color: #c2125c;
    border-color: rgba(194, 18, 92, 0.2);
  }

  body.theme-blossom .nav-links a:hover {
    border-color: #c2125c;
  }

  body.theme-blossom .hero-summary,
  body.theme-blossom .status-line,
  body.theme-blossom .status-detail,
  body.theme-blossom .theme-label,
  body.theme-blossom .autopilot-note,
  body.theme-blossom .panel-header p,
  body.theme-blossom .senator-meta,
  body.theme-blossom .amendment-meta p {
    color: #7c2354;
  }

  body.theme-blossom .pill,
  body.theme-blossom .tag {
    background: rgba(255, 155, 207, 0.25);
    border-color: rgba(255, 155, 207, 0.7);
    color: #7c2354;
  }

  body.theme-blossom .status-pill {
    background: #ff8ac3;
    color: #4d0a2d;
  }

  body.theme-blossom .pill-button {
    background: linear-gradient(120deg, #ff4fa3, #ff8ed6);
    color: #fff;
    box-shadow: 0 12px 20px rgba(255, 79, 163, 0.4);
  }

  body.theme-blossom .pill-button:hover {
    opacity: 1;
    filter: brightness(1.05);
  }

  body.theme-blossom .theme-button {
    border-color: rgba(255, 155, 207, 0.8);
    background: rgba(255, 255, 255, 0.8);
    color: #a51c55;
  }

  body.theme-blossom .theme-button.is-active {
    background: #ff4fa3;
    color: #fff;
  }

  body.theme-blossom .panel,
  body.theme-blossom .card,
  body.theme-blossom .turn-card,
  body.theme-blossom .amendment-card {
    background: rgba(255, 255, 255, 0.92);
    border-color: rgba(255, 155, 207, 0.6);
    box-shadow: 0 12px 30px rgba(255, 155, 207, 0.35);
  }

  body.theme-blossom .empty-transcript {
    background: rgba(255, 235, 246, 0.9);
    border-color: rgba(255, 155, 207, 0.6);
    color: #872150;
  }

  body.theme-blossom .alert {
    background: rgba(255, 182, 193, 0.25);
    border-color: #ff4fa3;
    color: #b81052;
  }

  body.theme-blossom .transcript-block pre {
    background: rgba(255, 230, 240, 0.9);
    color: #6d1c42;
  }

  body.theme-blossom .senator-bio,
  body.theme-blossom .bill-summary,
  body.theme-blossom .amendment-text,
  body.theme-blossom .turn-text p {
    color: #5d1a3d;
  }

  body.theme-signal {
    background: linear-gradient(135deg, #f5f5f5, #dcdcdc);
    color: #111;
    font-family: 'Futura', 'Bahnschrift', 'Arial Narrow', sans-serif;
    text-transform: none;
  }

  body.theme-signal .hero {
    background: #fff;
    border: 4px solid #111;
    border-bottom: 12px solid #d40000;
    box-shadow: 0 25px 40px rgba(0, 0, 0, 0.2);
  }

  body.theme-signal .nav-links a {
    color: #111;
    border-color: rgba(17, 17, 17, 0.35);
  }

  body.theme-signal .nav-links a:hover {
    border-color: #d40000;
  }

  body.theme-signal .hero-summary,
  body.theme-signal .status-line,
  body.theme-signal .status-detail,
  body.theme-signal .theme-label,
  body.theme-signal .autopilot-note,
  body.theme-signal .panel-header p,
  body.theme-signal .senator-meta,
  body.theme-signal .amendment-meta p {
    color: #1f1f1f;
  }

  body.theme-signal .pill,
  body.theme-signal .tag {
    background: #f7f7f7;
    border: 2px solid #111;
    color: #111;
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  body.theme-signal .status-pill {
    background: #d40000;
    color: #fff;
  }

  body.theme-signal .pill-button {
    background: #111;
    color: #fff;
    text-transform: uppercase;
    letter-spacing: 0.15em;
    border-radius: 0;
    padding: 0.6rem 1.6rem;
  }

  body.theme-signal .pill-button:hover {
    background: #d40000;
  }

  body.theme-signal .theme-button {
    border: 2px solid #111;
    background: #fff;
    color: #111;
    text-transform: uppercase;
  }

  body.theme-signal .theme-button.is-active {
    background: #d40000;
    color: #fff;
  }

  body.theme-signal .panel,
  body.theme-signal .card,
  body.theme-signal .turn-card,
  body.theme-signal .amendment-card {
    background: #fff;
    border: 3px solid #111;
    box-shadow: 12px 12px 0 #111;
  }

  body.theme-signal .empty-transcript {
    border: 3px dashed #111;
    color: #333;
    background: #fafafa;
  }

  body.theme-signal .alert {
    background: #fff0f0;
    border: 3px solid #d40000;
    color: #760000;
  }

  body.theme-signal .transcript-block pre {
    background: #f6f6f6;
    color: #111;
  }

  body.theme-orbit {
    background: radial-gradient(circle at 10% 20%, #0b1b2a, #030914);
    color: #e6f3ff;
    font-family: 'Orbitron', 'Share Tech Mono', 'Segoe UI', sans-serif;
    letter-spacing: 0.01em;
  }

  body.theme-orbit .hero {
    background: rgba(2, 9, 26, 0.9);
    border: 1px solid #5af1ff;
    box-shadow: 0 0 40px rgba(90, 241, 255, 0.25);
  }

  body.theme-orbit .nav-links a {
    color: #9be7ff;
    border-color: rgba(90, 241, 255, 0.25);
  }

  body.theme-orbit .nav-links a:hover {
    border-color: #5af1ff;
  }

  body.theme-orbit .hero-summary,
  body.theme-orbit .status-line,
  body.theme-orbit .status-detail,
  body.theme-orbit .theme-label,
  body.theme-orbit .autopilot-note,
  body.theme-orbit .panel-header p,
  body.theme-orbit .senator-meta,
  body.theme-orbit .amendment-meta p {
    color: #b4f3ff;
  }

  body.theme-orbit .pill,
  body.theme-orbit .tag {
    background: rgba(90, 241, 255, 0.12);
    border-color: rgba(90, 241, 255, 0.35);
    color: #bdf8ff;
  }

  body.theme-orbit .status-pill {
    background: rgba(90, 241, 255, 0.3);
    color: #03111f;
  }

  body.theme-orbit .pill-button {
    background: linear-gradient(135deg, #10b8ff, #62ffe1);
    color: #02101c;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    box-shadow: 0 0 25px rgba(98, 255, 225, 0.45);
  }

  body.theme-orbit .pill-button:hover {
    filter: brightness(1.1);
  }

  body.theme-orbit .theme-button {
    border-color: rgba(90, 241, 255, 0.5);
    background: rgba(2, 14, 24, 0.85);
    color: #9be7ff;
  }

  body.theme-orbit .theme-button.is-active {
    background: #5af1ff;
    color: #03111f;
  }

  body.theme-orbit .panel,
  body.theme-orbit .card,
  body.theme-orbit .turn-card,
  body.theme-orbit .amendment-card {
    background: rgba(5, 20, 36, 0.95);
    border: 1px solid rgba(90, 241, 255, 0.25);
    box-shadow: 0 0 35px rgba(0, 0, 0, 0.6);
  }

  body.theme-orbit .empty-transcript {
    background: rgba(6, 26, 46, 0.9);
    border-color: rgba(90, 241, 255, 0.2);
    color: #c4fbff;
  }

  body.theme-orbit .alert {
    background: rgba(255, 123, 123, 0.14);
    border-color: rgba(255, 144, 144, 0.5);
    color: #ffd7d7;
  }

  body.theme-orbit .transcript-block pre {
    background: #07192a;
    color: #d6f9ff;
  }

  body.theme-orbit .senator-bio,
  body.theme-orbit .bill-summary,
  body.theme-orbit .amendment-text,
  body.theme-orbit .turn-text p {
    color: #e6f3ff;
  }

  body.theme-romance {
    background: radial-gradient(circle at 20% 20%, #fff0f3, #ffe1e7, #ffd6e1);
    color: #5c1121;
    font-family: 'Playfair Display', 'Cormorant Garamond', serif;
  }

  body.theme-romance .hero {
    background: rgba(255, 255, 255, 0.9);
    border-color: #f76c8c;
    box-shadow: 0 15px 30px rgba(247, 108, 140, 0.35);
  }

  body.theme-romance .nav-links a {
    color: #b1132f;
    border-color: rgba(177, 19, 47, 0.2);
  }

  body.theme-romance .nav-links a:hover {
    border-color: #b1132f;
  }

  body.theme-romance .hero-summary,
  body.theme-romance .status-line,
  body.theme-romance .status-detail,
  body.theme-romance .theme-label,
  body.theme-romance .autopilot-note,
  body.theme-romance .panel-header p,
  body.theme-romance .senator-meta,
  body.theme-romance .amendment-meta p {
    color: #7a1a2c;
  }

  body.theme-romance .pill,
  body.theme-romance .tag {
    background: rgba(255, 167, 186, 0.3);
    border-color: rgba(255, 87, 120, 0.5);
    color: #7a1a2c;
  }

  body.theme-romance .status-pill {
    background: #ff5f87;
    color: #fff;
  }

  body.theme-romance .pill-button {
    background: linear-gradient(120deg, #d70040, #ff5f87);
    color: #fff;
    border-radius: 999px;
    box-shadow: 0 12px 24px rgba(215, 0, 64, 0.35);
  }

  body.theme-romance .pill-button:hover {
    filter: brightness(1.1);
  }

  body.theme-romance .theme-button {
    border-color: rgba(255, 87, 120, 0.6);
    color: #b1132f;
    background: rgba(255, 255, 255, 0.85);
  }

  body.theme-romance .theme-button.is-active {
    background: #d70040;
    color: #fff;
  }

  body.theme-romance .panel,
  body.theme-romance .card,
  body.theme-romance .turn-card,
  body.theme-romance .amendment-card {
    background: rgba(255, 255, 255, 0.95);
    border-color: rgba(255, 87, 120, 0.4);
    box-shadow: 0 15px 30px rgba(215, 0, 64, 0.2);
  }

  body.theme-romance .empty-transcript {
    background: rgba(255, 230, 236, 0.9);
    border-color: rgba(255, 87, 120, 0.4);
    color: #7a1a2c;
  }

  body.theme-romance .alert {
    background: rgba(255, 147, 165, 0.3);
    border-color: #d70040;
    color: #7a1a2c;
  }

  body.theme-romance .transcript-block pre {
    background: rgba(255, 237, 241, 0.95);
    color: #7a1a2c;
  }

  body.theme-romance .senator-bio,
  body.theme-romance .bill-summary,
  body.theme-romance .amendment-text,
  body.theme-romance .turn-text p {
    color: #5c1121;
  }

  @media (max-width: 720px) {
    .grid {
      grid-template-columns: 1fr;
    }
  }
  "
}
