import debate
import gleam/int
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import senators
import session

const max_turns = 10

pub fn render_session_page(
  sess: session.Session,
  senators_list: List(senators.Senator),
  autopilot_state: Option(Bool),
) -> String {
  let bill_section = render_bill(sess.bill)
  let debate_section = render_debate_log(sess)
  let amendment_section = render_amendments(sess.amendments)
  let roster_section = render_roster(sess, senators_list)
  let error_section = render_error_banner(sess.last_error)
  let status_line = render_status_line(sess)
  let autopilot_controls = render_autopilot_controls(autopilot_state)

  "<!doctype html>
   <html lang=\"en\">
     <head>
       <meta charset=\"utf-8\" />
       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
       <title>Harmony Chamber</title>
       <style>" <> stylesheet() <> "</style>
     </head>
     <body>
       <div class=\"page\">
         <header class=\"hero\">
           <div>
             <p class=\"eyebrow\">Harmony Chamber</p>
             <h1>Multi-Agent Senate Simulation</h1>
             <p class=\"hero-summary\">
               Live session generated by Gleam/BEAM + OpenAI agents.
             </p>
             <p>
               LLM calls used: " <> int.to_string(sess.llm_calls_used) <> " / " <> int.to_string(
    sess.llm_calls_limit,
  ) <> "
             </p>
             " <> status_line <> "
             " <> autopilot_controls <> "
           </div>
         </header>
         " <> error_section <> "
         <main class=\"grid\">
           " <> bill_section <> "
           " <> debate_section <> "
           " <> amendment_section <> "
         </main>
         " <> roster_section <> "
       </div>
     </body>
   </html>"
}

fn render_bill(bill: session.Bill) -> String {
  "<section class=\"panel bill-panel\">
     <div class=\"panel-header\">
       <h2>" <> escape_html(bill.title) <> "</h2>
       <p class=\"bill-id\">Bill " <> escape_html(bill.id) <> "</p>
     </div>
     <p class=\"bill-summary\">" <> escape_html(bill.summary) <> "</p>
   </section>"
}

fn render_debate_log(sess: session.Session) -> String {
  let turns =
    sess.debate_turns
    |> list.reverse
    |> list.take(max_turns)
    |> list.reverse

  let body = case turns {
    [] ->
      "<div class=\"empty-transcript\">
         <p>No speeches logged yet. Senators are still reviewing the bill.</p>
       </div>"
    _ ->
      turns
      |> list.map(render_turn_card)
      |> string.join("")
  }

  "<section class=\"panel transcript-panel\">
     <div class=\"panel-header\">
       <h2>Debate Floor</h2>
       <p>The most recent " <> int.to_string(max_turns) <> " turns appear below.</p>
     </div>
     <div class=\"transcript-grid\">" <> body <> "</div>
   </section>"
}

fn render_turn_card(turn: debate.DebateTurn) -> String {
  "<article class=\"turn-card\">
     <div class=\"turn-meta\">
       <span class=\"turn-index\">Turn #" <> int.to_string(turn.turn_index) <> "</span>
       <span class=\"turn-senator\">" <> escape_html(turn.senator.name) <> " (" <> escape_html(
    turn.senator.state,
  ) <> ")</span>
       <span class=\"turn-vote\">" <> escape_html(debate.vote_intent_label(
    turn.vote_intent,
  )) <> "</span>
     </div>
     " <> render_turn_tags(turn) <> "
     <div class=\"turn-text\">" <> format_speech(turn.speech) <> "</div>
   </article>"
}

fn render_turn_tags(turn: debate.DebateTurn) -> String {
  let purpose = string.trim(turn.purpose)

  let purpose_tag =
    case purpose {
      "" -> ""
      _ -> "<span class=\"pill tag\">Purpose: " <> escape_html(purpose) <> "</span>"
    }

  let procedure_tag =
    case turn.procedure {
      debate.NoProcedure -> ""
      _ ->
        "<span class=\"pill tag\">Procedure: " <> escape_html(
          debate.procedure_label(turn.procedure),
        ) <> "</span>"
    }

  let tags =
    [purpose_tag, procedure_tag]
    |> list.filter(fn(tag) { tag != "" })
    |> string.join("")

  case tags {
    "" -> ""
    _ -> "<div class=\"turn-tags\">" <> tags <> "</div>"
  }
}

fn render_amendments(amendments: List(session.Amendment)) -> String {
  let content = case amendments {
    [] ->
      "<div class=\"empty-transcript\">
         <p>No amendments proposed yet. Senators may submit a full replacement text.</p>
       </div>"
    _ ->
      amendments
      |> list.map(render_amendment_card)
      |> string.join("")
  }

  "<section class=\"panel amendment-panel\">
     <div class=\"panel-header\">
       <h2>Amendments</h2>
       <p>Each amendment replaces the bill text if adopted.</p>
     </div>
     <div class=\"amendment-list\">" <> content <> "</div>
   </section>"
}

fn render_amendment_card(amendment: session.Amendment) -> String {
  let vote_summary = case amendment.vote_result {
    None -> ""
    Some(result) ->
      "<p class=\"amendment-vote\">Vote: " <> escape_html(
        format_result_summary(result),
      ) <> "</p>"
  }

  "<article class=\"card amendment-card\">
     <div class=\"amendment-meta\">
       <h3>Amendment " <> int.to_string(amendment.id) <> "</h3>
       <p>Proposed by " <> escape_html(amendment.proposer.name) <> "</p>
       <p>Status: " <> escape_html(format_amendment_status(amendment.status)) <> "</p>
       " <> vote_summary <> "
     </div>
     <div class=\"amendment-text\">" <> format_speech(amendment.text) <> "</div>
   </article>"
}

fn render_roster(
  sess: session.Session,
  senators_list: List(senators.Senator),
) -> String {
  let cards =
    senators_list
    |> list.map(fn(senator) {
      let intent = case session.vote_intent_for(sess, senator.id) {
        Some(value) -> value
        None -> debate.Undecided
      }

      "<article class=\"card senator-card\">
         <h3>" <> escape_html(senator.name) <> "</h3>
         <p class=\"senator-meta\">" <> escape_html(senator.state) <> " &middot; Vote intent: " <> escape_html(
        debate.vote_intent_label(intent),
      ) <> "</p>
         <p class=\"senator-bio\">" <> escape_html(biography_snippet(
        senator.biography,
      )) <> "</p>
       </article>"
    })
    |> string.join("")

  "<section class=\"panel senator-panel\">
     <div class=\"panel-header\">
       <h2>Senatorial Ledger</h2>
       <p>Background summaries and current vote intentions.</p>
     </div>
     <div class=\"senator-grid\">" <> cards <> "</div>
   </section>"
}

fn render_error_banner(error: Option(String)) -> String {
  case error {
    None -> ""
    Some(message) -> "<div class=\"alert\">
         <p>LLM decision error: " <> escape_html(message) <> "</p>
       </div>"
  }
}

fn render_status_line(sess: session.Session) -> String {
  let label = status_label(sess.status)

  let result_text =
    case sess.final_result {
      None -> ""
      Some(result) -> "Result: " <> format_result_summary(result)
    }

  let note =
    case sess.status {
      session.Closed ->
        "Deliberations closed. No further LLM calls will be made for this bill."
      session.Voting(session.BillVote) ->
        "Voting on the bill text is in progress. Tallies will finalize shortly."
      session.Voting(session.AmendmentVote(id)) ->
        "Voting on amendment " <> int.to_string(id) <> " is underway."
      session.InDebate ->
        "Debate in progress. Senators speak selectively with purpose."
    }

  let details =
    [result_text, note]
    |> list.filter(fn(text) { string.trim(text) != "" })
    |> list.map(escape_html)
    |> string.join(" · ")

  "<p class=\"status-line\"><span class=\"pill status-pill\">"
    <> escape_html(label)
    <> "</span> <span class=\"status-detail\">"
    <> details
    <> "</span></p>"
}

fn status_label(status: session.SessionStatus) -> String {
  case status {
    session.InDebate -> "In debate"
    session.Voting(session.BillVote) -> "Voting on bill"
    session.Voting(session.AmendmentVote(id)) ->
      "Voting on amendment " <> int.to_string(id)
    session.Closed -> "Closed"
  }
}

fn render_autopilot_controls(state: Option(Bool)) -> String {
  case state {
    None -> "<p class=\"autopilot-note\">Autopilot disabled — manual refresh required.</p>"
    Some(True) ->
      "<div class=\"control-bar\">
         <form action=\"/autopilot/pause\" method=\"post\">
           <button class=\"pill-button\" type=\"submit\">Pause Autopilot</button>
         </form>
         <p class=\"autopilot-note\">Autopilot running</p>
       </div>"
    Some(False) ->
      "<div class=\"control-bar\">
         <form action=\"/autopilot/resume\" method=\"post\">
           <button class=\"pill-button\" type=\"submit\">Resume Autopilot</button>
         </form>
         <p class=\"autopilot-note\">Autopilot paused</p>
       </div>"
  }
}

fn format_amendment_status(status: session.AmendmentStatus) -> String {
  case status {
    session.Pending -> "Pending"
    session.Adopted -> "Adopted"
    session.Rejected -> "Rejected"
  }
}

fn format_result_summary(result: session.VoteResult) -> String {
  let session.VoteResult(tally: tally, passed: passed) = result
  let session.VoteTally(yea: yea, nay: nay, abstain: abstain) = tally
  let verdict = case passed {
    True -> "Passed"
    False -> "Failed"
  }

  let abstain_suffix = case abstain > 0 {
    True -> " (" <> int.to_string(abstain) <> " abstaining)"
    False -> ""
  }

  verdict
    <> " "
    <> int.to_string(yea)
    <> "-"
    <> int.to_string(nay)
    <> abstain_suffix
}

fn biography_snippet(bio: String) -> String {
  let paragraphs = string.split(bio, "\n\n")
  let snippet = case paragraphs {
    [] -> bio
    [first, ..] -> first
  }

  case string.length(snippet) > 280 {
    True -> string.slice(snippet, 0, 277) <> "..."
    False -> snippet
  }
}

fn format_speech(text: String) -> String {
  case string.trim(text) {
    "" -> "<p>(No speech recorded this turn.)</p>"
    cleaned ->
      cleaned
      |> string.split("\n\n")
      |> list.map(fn(paragraph) { "<p>" <> escape_html(paragraph) <> "</p>" })
      |> string.join("")
  }
}

fn escape_html(text: String) -> String {
  text
  |> string.replace("&", "&amp;")
  |> string.replace("<", "&lt;")
  |> string.replace(">", "&gt;")
  |> string.replace("\"", "&quot;")
  |> string.replace("'", "&#39;")
}

fn stylesheet() -> String {
  "
  :root {
    --parchment: #f3efe2;
    --ink: #2d2a24;
    --accent: #c1a364;
    --shadow: rgba(0, 0, 0, 0.08);
  }

  * { box-sizing: border-box; }

  body {
    margin: 0;
    font-family: 'Georgia', 'Garamond', serif;
    background: var(--parchment);
    color: var(--ink);
  }

  .page {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem 1.5rem 4rem;
  }

  .hero {
    background: #f9f5ea;
    border: 2px solid var(--accent);
    border-radius: 1rem;
    padding: 1.5rem 2rem;
    box-shadow: 0 10px 30px var(--shadow);
    margin-bottom: 1.5rem;
  }

  .eyebrow {
    text-transform: uppercase;
    letter-spacing: 0.2em;
    font-size: 0.8rem;
    margin: 0 0 0.4rem;
    color: #8c6a2f;
  }

  .hero-summary {
    margin: 0.4rem 0 0;
    max-width: 40rem;
  }

  .status-line {
    margin: 0.5rem 0 0;
    font-weight: 600;
    color: #5a4a30;
  }

  .status-detail {
    font-weight: 400;
    margin-left: 0.5rem;
  }

  .pill {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
    padding: 0.25rem 0.75rem;
    border-radius: 999px;
    background: #e8dcc0;
    border: 1px solid #c1a364;
    font-size: 0.85rem;
    letter-spacing: 0.02em;
  }

  .status-pill {
    background: #d9c28d;
  }

  .control-bar {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
    align-items: center;
    margin-top: 0.75rem;
  }

  .pill-button {
    border: none;
    background: #2d2a24;
    color: #fff;
    padding: 0.45rem 1.1rem;
    border-radius: 999px;
    font-size: 0.9rem;
    cursor: pointer;
    transition: opacity 0.15s ease;
  }

  .pill-button:hover {
    opacity: 0.85;
  }

  .autopilot-note {
    margin: 0;
    color: #5a4a30;
    font-size: 0.9rem;
  }

  .alert {
    background: #fff2e4;
    border: 1px solid #d27c35;
    border-radius: 0.5rem;
    padding: 0.75rem 1rem;
    margin-bottom: 1rem;
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 1.5rem;
    margin-bottom: 2rem;
  }

  .panel {
    background: #fffdf8;
    border: 2px solid #dac6a3;
    border-radius: 1rem;
    padding: 1.5rem;
    box-shadow: 0 8px 24px var(--shadow);
  }

  .panel-header h2 {
    margin: 0;
    font-size: 1.4rem;
  }

  .panel-header p {
    margin: 0.3rem 0 0;
    color: #5a4a30;
  }

  .bill-summary {
    line-height: 1.6;
  }

  .transcript-grid {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .turn-card {
    background: #fffaf0;
    border: 1px solid rgba(151, 121, 70, 0.4);
    border-radius: 0.75rem;
    padding: 1rem;
    box-shadow: 0 6px 20px var(--shadow);
  }

  .turn-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem 1rem;
    font-size: 0.9rem;
    margin-bottom: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #6f5632;
  }

  .turn-text p {
    margin: 0 0 0.6rem;
    line-height: 1.55;
  }

  .turn-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 0.4rem;
    margin: 0 0 0.5rem;
  }

  .tag {
    background: #f1e6d0;
  }

  .empty-transcript {
    border: 1px dashed #c5ab78;
    border-radius: 0.75rem;
    padding: 1rem;
    font-style: italic;
    color: #6b5a37;
  }

  .senator-panel {
    margin-top: 2rem;
  }

  .senator-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 1rem;
    margin-top: 1rem;
  }

  .card {
    background: #fffef9;
    border: 1px solid rgba(149, 115, 60, 0.35);
    border-radius: 0.75rem;
    padding: 1rem;
    box-shadow: 0 4px 16px var(--shadow);
  }

  .senator-card h3 {
    margin: 0;
  }

  .senator-meta {
    margin: 0.35rem 0;
    font-size: 0.95rem;
    color: #6a5533;
  }

  .senator-bio {
    margin: 0;
    line-height: 1.4;
  }

  .amendment-panel .amendment-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin-top: 1rem;
  }

  .amendment-card h3 {
    margin: 0 0 0.25rem 0;
  }

  .amendment-meta p {
    margin: 0.1rem 0;
    font-size: 0.9rem;
    color: #5b4a33;
  }

  .amendment-text {
    margin-top: 0.5rem;
  }

  .amendment-text p {
    margin: 0 0 0.6rem;
  }

  .amendment-vote {
    font-weight: 600;
  }

  @media (max-width: 720px) {
    .grid {
      grid-template-columns: 1fr;
    }
  }
  "
}
