//// Harmony Chamber senator roster
//// Comprehensive biographies for all 100 senators.

pub type Senator {
  Senator(id: String, name: String, state: String, biography: String)
}

pub fn all() -> List(Senator) {
  [
    Senator(
      id: "katie_britt",
      name: "Katie Britt",
      state: "Alabama",
      biography: "Katie Britt was born in Enterprise, Alabama and grew up helping her parents run a small construction firm before heading to cheer practice or 4-H meetings.\n\nShe studied at the University of Alabama for both undergraduate and law degrees and built a career as a congressional aide who became chief of staff to Senator Richard Shelby and later president of the Business Council of Alabama. Those roles put her in the middle of port dredging talks, hurricane recovery plans, and apprenticeship expansions across the Gulf Coast.\n\nElected in 2022 as Alabama's first female senator, she now focuses on workforce training, coastal infrastructure, and maternal health clinics, often citing long drives between Wiregrass towns to explain the stakes.",
    ),
    Senator(
      id: "tommy_tuberville",
      name: "Tommy Tuberville",
      state: "Alabama",
      biography: "Tommy Tuberville was born in Camden, Arkansas and spent his childhood bouncing between military towns before settling in the South, where football fields became his second home.\n\nHe studied at Southern Arkansas University and built a career as a high-school coach turned collegiate head coach who led Ole Miss and Auburn and later hosted leadership camps and charity tournaments across Alabama. Decades on the sideline taught him to recruit talent, manage staffs, and navigate booster politics.\n\nWinning a Senate seat in 2020, he now draws on that playbook when pressing for agricultural research, military housing upgrades, and a national framework for college athlete compensation.",
    ),
    Senator(
      id: "lisa_murkowski",
      name: "Lisa Murkowski",
      state: "Alaska",
      biography: "Lisa Murkowski was born in Ketchikan, Alaska and was raised in small fishing towns along the Inside Passage, where floatplanes doubled as school buses and winter storms directed grocery runs.\n\nShe studied at Georgetown University and Willamette University College of Law and built a career as worked as an Anchorage attorney and served in the Alaska House, focusing on land-use and rural energy policy. She honed bipartisan skills chairing the state House Labor and Commerce Committee.\n\nAppointed in 2002 and famous for her 2010 write-in victory, Murkowski champions Arctic research, Coast Guard infrastructure, and reproductive healthcare access.",
    ),
    Senator(
      id: "dan_sullivan",
      name: "Dan Sullivan",
      state: "Alaska",
      biography: "Dan Sullivan was born in Fairview Park, Ohio and spent summers fishing the Kenai before moving north full time, blending Midwestern roots with Alaska's frontier ethic.\n\nHe studied at Harvard University and Georgetown University Law Center and built a career as served as a Marine Corps officer, clerked on the D.C. Circuit, and held national security posts before becoming Alaska's attorney general and commissioner of natural resources. He led multistate fights over the Endangered Species Act and offshore development.\n\nElected in 2014, Sullivan focuses on Arctic shipping lanes, defense modernization, and veterans mental health, often drilling with his Marine reserve unit on weekends.",
    ),
    Senator(
      id: "kyrsten_sinema",
      name: "Kyrsten Sinema",
      state: "Arizona",
      biography: "Kyrsten Sinema was born in Tucson, Arizona and spent part of her childhood living in an abandoned gas station in Florida after her parents' divorce, an experience that shaped her views on housing security.\n\nShe studied at Brigham Young University, Arizona State University, and later Harvard's Kennedy School for a mid-career master's and built a career as a social worker and attorney who represented immigrants, victims of domestic violence, and children in foster care before winning seats in the Arizona Legislature and U.S. House. Her policy work frequently blended behavioral health expertise with fiscal pragmatism.\n\nElected to the Senate in 2018 and now an independent, she is known for shuttle diplomacy on infrastructure, gun safety, and tax credits, insisting that durable deals require patient listening sessions back home in Phoenix and Flagstaff.",
    ),
    Senator(
      id: "mark_kelly",
      name: "Mark Kelly",
      state: "Arizona",
      biography: "Mark Kelly was born in West Orange, New Jersey and was raised by two police officers who encouraged him and his twin brother to explore tinkering projects in the family garage.\n\nHe studied at the U.S. Merchant Marine Academy and later the U.S. Naval Postgraduate School and built a career as a Navy combat pilot who flew 39 combat missions during Operation Desert Storm before becoming a NASA astronaut and commanding two shuttle missions. After his wife Gabby Giffords survived a 2011 assassination attempt, he co-founded an organization focused on ending gun violence.\n\nKelly won a special election in 2020 and a full term in 2022, bringing astronaut-style checklists to debates on water security, semiconductor manufacturing, and support for military families stationed at Arizona bases.",
    ),
    Senator(
      id: "john_boozman",
      name: "John Boozman",
      state: "Arkansas",
      biography: "John Boozman was born in Shreveport, Louisiana and moved with his Air Force family to Fort Smith, Arkansas, where he balanced 4-H judging with helping on the family farm.\n\nHe studied at the University of Arkansas and the Southern College of Optometry and built a career as an optometrist who co-founded a clinic in Rogers before serving on the school board and running large-scale vision programs for low-income kids. His medical practice introduced him to veterans and poultry workers facing preventable blindness, which influenced his later legislation.\n\nAfter a decade in the U.S. House he entered the Senate in 2011, focusing on veterans rehabilitation, agricultural research, and navigation upgrades along the McClellan–Kerr Arkansas River system.",
    ),
    Senator(
      id: "tom_cotton",
      name: "Tom Cotton",
      state: "Arkansas",
      biography: "Tom Cotton was born in Dardanelle, Arkansas and grew up on his family's cattle farm in Yell County, where long days of baling hay instilled a respect for rural grit.\n\nHe studied at Harvard College and Harvard Law School and built a career as an Army infantry officer who deployed to Iraq and Afghanistan before clerking for a federal judge and practicing law. His 2006 letter challenging the New York Times over classified information thrust him into the national security debate.\n\nElected to the Senate in 2014 after one term in the House, Cotton is a leading voice on defense, intelligence, and supply-chain resilience, often referencing Ranger School lessons on preparation.",
    ),
    Senator(
      id: "laphonza_butler",
      name: "Laphonza Butler",
      state: "California",
      biography: "Laphonza Butler was born in Magnolia, Mississippi and was raised by a widowed mother who worked multiple jobs, giving Butler firsthand insight into the sacrifices of home health aides and domestic workers.\n\nShe studied at Jackson State University and built a career as a union organizer who moved to California to help care workers and janitors win better wages before leading SEIU Local 2015 and later EMILY's List. Her campaigns often paired contract negotiations with leadership academies for women of color.\n\nAppointed in 2023 after the death of Senator Dianne Feinstein, Butler has emphasized voting rights, reproductive healthcare, and the logistics of caregiving, drawing on two decades spent at the negotiating table.",
    ),
    Senator(
      id: "alex_padilla",
      name: "Alex Padilla",
      state: "California",
      biography: "Alex Padilla was born in Los Angeles, California and is the son of Mexican immigrants who worked as a short-order cook and a housekeeper, and he often translated paperwork for neighbors in Pacoima.\n\nHe studied at the Massachusetts Institute of Technology, where he studied mechanical engineering and built a career as a Los Angeles city councilmember who later served in the California Senate and as California's secretary of state, modernizing election technology and automatic voter registration. Padilla's engineering mindset led him to focus on seismic upgrades to water and rail systems.\n\nAppointed in 2021 and elected the following year, he now champions immigration reform, wildfire resilience, and STEM education pipelines for students from working-class families like his own.",
    ),
    Senator(
      id: "michael_bennet",
      name: "Michael Bennet",
      state: "Colorado",
      biography: "Michael Bennet was born in New Delhi, India and grew up in Washington, D.C., where his diplomat father served successive presidents and exposed him to public service debates at the dinner table.\n\nHe studied at Wesleyan University and Yale Law School and built a career as a corporate lawyer who became chief of staff to Denver Mayor John Hickenlooper before running the Denver Public Schools, where he pushed innovative financing to renovate aging buildings. His school turnaround work inspired the early-childhood provisions later embedded in federal policy.\n\nAppointed to the Senate in 2009 and subsequently elected, Bennet focuses on child tax credits, wildfire mitigation, and bipartisan immigration fixes, often referencing both classroom visits and Western water tours.",
    ),
    Senator(
      id: "john_hickenlooper",
      name: "John Hickenlooper",
      state: "Colorado",
      biography: "John Hickenlooper was born in Narberth, Pennsylvania and was raised by a widowed mother who taught him thrift and curiosity, habits he fed by collecting rocks and running science experiments in the basement.\n\nHe studied at Wesleyan University and the Colorado School of Mines for post-graduate geology coursework and built a career as a petroleum geologist who co-founded Denver's first brewpub after a layoff, sparking the revitalization of LoDo and later serving as Denver mayor and Colorado governor. His entrepreneurial streak led to transit expansions, creative arts districts, and statewide broadband mapping.\n\nElected to the Senate in 2020, Hickenlooper now brings that operator's mindset to work on infrastructure implementation, advanced energy, and the ethics of commercial spaceflight.",
    ),
    Senator(
      id: "richard_blumenthal",
      name: "Richard Blumenthal",
      state: "Connecticut",
      biography: "Richard Blumenthal was born in Brooklyn, New York and spent weekends at Coney Island with his immigrant parents, developing a lifelong focus on consumer protection and public safety.\n\nHe studied at Harvard College, Cambridge University, and Yale Law School and built a career as a U.S. Marine Corps Reserve captain who later served as U.S. Attorney for Connecticut and then as the state's attorney general for two decades. He became known for suing price-fixing cartels, tobacco companies, and predatory lenders.\n\nIn the Senate since 2011, Blumenthal channels that prosecutorial energy into veterans benefits, rail safety, and tech accountability, always reminding audiences that courtrooms and committee rooms share the same demand for facts.",
    ),
    Senator(
      id: "chris_murphy",
      name: "Chris Murphy",
      state: "Connecticut",
      biography: "Chris Murphy was born in Wethersfield, Connecticut and was the son of a community college instructor and homemaker who volunteered at local libraries, instilling a love of public service.\n\nHe studied at Williams College and the University of Connecticut School of Law and built a career as a state legislator who went on to serve three terms in the U.S. House, where he specialized in transportation and consumer issues. After the Sandy Hook shooting in his district, he became one of Congress's most visible advocates for gun violence prevention.\n\nSince joining the Senate in 2013 he has led bipartisan talks on background checks, youth mental health, and NATO policy, often linking his proposals to town hall conversations with grieving families.",
    ),
    Senator(
      id: "tom_carper",
      name: "Tom Carper",
      state: "Delaware",
      biography: "Tom Carper was born in Beckley, West Virginia and grew up in a working-class family before earning a Navy ROTC scholarship that launched him into military aviation.\n\nHe studied at Ohio State University and the University of Delaware for an MBA and built a career as a Navy flight officer and Vietnam veteran who later served as Delaware state treasurer, U.S. congressman, and governor. His gubernatorial years emphasized fiscal discipline, brownfield cleanup, and the launch of the Delaware Air National Guard's C-130 fleet.\n\nServing in the Senate since 2001, Carper is the last Vietnam veteran in the chamber and focuses on postal reform, clean energy manufacturing, and Amtrak's Northeast Corridor, all while mentoring the next generation of Delaware leaders.",
    ),
    Senator(
      id: "chris_coons",
      name: "Chris Coons",
      state: "Delaware",
      biography: "Chris Coons was born in Greenwich, Connecticut and was raised in Hockessin, Delaware, where scouting trips and mission work sparked an early interest in faith-driven service.\n\nHe studied at Amherst College and Yale, where he earned both a law degree and a Master of Divinity and built a career as counsel for W.L. Gore & Associates who later served as president of the New Castle County Council and county executive. He became known for balancing budgets during the Great Recession without slashing core services.\n\nElected in 2010, Coons is now a leading voice on foreign relations, patent policy, and workforce apprenticeships, frequently convening bipartisan prayer breakfasts and manufacturing roundtables.",
    ),
    Senator(
      id: "marco_rubio",
      name: "Marco Rubio",
      state: "Florida",
      biography: "Marco Rubio was born in Miami, Florida and was raised by Cuban immigrant parents who worked as a bartender and hotel maid, and he spent childhood summers with relatives in Las Vegas and South Florida.\n\nHe studied at the University of Florida and the University of Miami School of Law and built a career as a city commissioner and speaker of the Florida House who championed property tax reform and teacher pay raises while teaching night classes. His 2006 book of policy blueprints helped modernize the state GOP's agenda.\n\nSince 2011 he has served on the intelligence and foreign relations committees, pushing for small-business relief after hurricanes and for a tougher line on authoritarian regimes.",
    ),
    Senator(
      id: "rick_scott",
      name: "Rick Scott",
      state: "Florida",
      biography: "Rick Scott was born in Bloomington, Illinois and grew up in public housing in Kansas City, watching his mother juggle retail jobs to keep the lights on.\n\nHe studied at the University of Missouri–Kansas City and Southern Methodist University School of Law and built a career as a Navy radar technician who later built Columbia/HCA into the nation's largest hospital company before turning to private equity. His turnaround work taught him to scrutinize budgets line by line.\n\nAfter two terms as Florida's governor, Scott joined the Senate in 2019 and now focuses on disaster preparedness, supply-chain redundancies, and fiscal restraint, often brandishing spreadsheets at hearings.",
    ),
    Senator(
      id: "jon_ossoff",
      name: "Jon Ossoff",
      state: "Georgia",
      biography: "Jon Ossoff was born in Atlanta, Georgia and was raised by an immigrant small-business owner and an executive at a children's hospital, spending weekends volunteering at civil rights museums and public schools.\n\nHe studied at Georgetown University's School of Foreign Service and the London School of Economics and built a career as an investigative journalist and CEO of a documentary film company that exposed corruption and war crimes on four continents. His productions helped free wrongfully jailed prisoners in Africa and Asia.\n\nElected in 2021 at age 33, Ossoff now leads bipartisan efforts on supply-chain security, clean-tech manufacturing in the South, and prison transparency, often referencing lessons from reporters and whistleblowers he once employed.",
    ),
    Senator(
      id: "raphael_warnock",
      name: "Raphael Warnock",
      state: "Georgia",
      biography: "Raphael Warnock was born in Savannah, Georgia and is the eleventh of twelve children who grew up in Kayton Homes public housing, where his father ran a small car-repair business under a shade tree.\n\nHe studied at Morehouse College and Union Theological Seminary and built a career as a Baptist pastor who led congregations in Baltimore and Harlem before becoming senior pastor at Ebenezer Baptist Church in Atlanta, once led by Martin Luther King Jr.. He helped expand Ebenezer's health clinic, housing ministry, and voter education programs.\n\nWarnock won special and regular elections in 2021 and 2022, bringing pulpit storytelling to debates on voting rights, agricultural equity, and student debt relief.",
    ),
    Senator(
      id: "brian_schatz",
      name: "Brian Schatz",
      state: "Hawaii",
      biography: "Brian Schatz was born in Ann Arbor, Michigan and moved to Honolulu as a toddler, where his parents taught at schools across Oahu and encouraged him to join debate club and canoe paddling teams.\n\nHe studied at Pomona College and built a career as a nonprofit leader who directed Helping Hands Hawaii before serving in the state legislature and as lieutenant governor. He helped launch the Hawaii Clean Energy Initiative, mapping a path to 100 percent renewables.\n\nAppointed in 2012 after Senator Daniel Inouye's death, Schatz now focuses on climate resiliency, broadband in the Pacific, and youth mental health, frequently reminding colleagues how sea-level rise threatens Waikiki and the Marshall Islands alike.",
    ),
    Senator(
      id: "mazie_hirono",
      name: "Mazie Hirono",
      state: "Hawaii",
      biography: "Mazie Hirono was born in Fukushima, Japan and immigrated to Honolulu at age eight with her mother and brothers, escaping an abusive marriage and starting anew in a public housing complex.\n\nShe studied at the University of Hawaii and Georgetown University Law Center and built a career as a state representative, lieutenant governor, and three-term U.S. representative who advocated for education funding and immigrant families. Her own experience learning English in Hawaii's public schools informs her policy work.\n\nSince 2013 Hirono has been one of the Senate's fiercest defenders of Title IX, maritime jobs, and veterans from the Asia-Pacific region, often hosting field hearings in Hilo, Maui, and Guam.",
    ),
    Senator(
      id: "mike_crapo",
      name: "Mike Crapo",
      state: "Idaho",
      biography: "Mike Crapo was born in Idaho Falls, Idaho and was one of nine siblings who took turns irrigating the family's alfalfa fields near the Snake River.\n\nHe studied at Brigham Young University and Harvard Law School and built a career as an attorney in Idaho Falls who served in the state senate, eventually becoming Senate president pro tempore before heading to the U.S. House. He specialized in water adjudication and forest management cases that crossed state lines.\n\nA senator since 1999, Crapo now shepherds tax, banking, and salmon recovery legislation, often highlighting how rural credit co-ops and tribal fisheries underpin the region's economy.",
    ),
    Senator(
      id: "jim_risch",
      name: "Jim Risch",
      state: "Idaho",
      biography: "Jim Risch was born in Milwaukee, Wisconsin and moved to Idaho as a teenager, working odd jobs in logging and on campus to pay tuition.\n\nHe studied at Boise State College and the University of Idaho College of Law and built a career as a prosecutor turned Ada County district attorney who later served as lieutenant governor and, briefly, governor of Idaho. He built a reputation for tough-but-pragmatic deals on wildfire response and property tax relief.\n\nSince 2009 Risch has used his foreign relations ranking seat to champion nuclear energy exports, agriculture diplomacy, and stronger alliances in the Indo-Pacific.",
    ),
    Senator(
      id: "dick_durbin",
      name: "Dick Durbin",
      state: "Illinois",
      biography: "Dick Durbin was born in East St. Louis, Illinois and worked evenings at his parents' small store before graduating from Assumption High School, the last class before the school closed.\n\nHe studied at Georgetown University and its law center and built a career as an attorney and aide to Senator Paul Douglas who later served in the Illinois House and then in the U.S. House starting in 1982. Durbin became known as an advocate for consumer safety, espionage law reform, and tobacco regulation.\n\nServing in the Senate since 1997, he is now majority whip and a leading voice on immigration, judgeships, and biomedical research funding at the University of Illinois system.",
    ),
    Senator(
      id: "tammy_duckworth",
      name: "Tammy Duckworth",
      state: "Illinois",
      biography: "Tammy Duckworth was born in Bangkok, Thailand and moved frequently across Southeast Asia before her family resettled in Honolulu, where she helped care for her younger brother while her parents rebuilt their careers.\n\nShe studied at the University of Hawaii, George Washington University, and later the Army's flight school and built a career as a helicopter pilot in the Illinois Army National Guard who lost both legs when her Black Hawk was shot down in Iraq, then led the Illinois Department of Veterans' Affairs and the federal VA's Office of Public and Intergovernmental Affairs. She championed accessible transit systems and adaptive sports programs for wounded warriors.\n\nElected in 2016, Duckworth focuses on caregiving tax credits, maternal health, and modernizing Guard equipment, often meeting newly injured service members before major votes.",
    ),
    Senator(
      id: "mike_braun",
      name: "Mike Braun",
      state: "Indiana",
      biography: "Mike Braun was born in Jasper, Indiana and spent summers baling hay and playing high school football in Dubois County, where his family ran a small trucking firm.\n\nHe studied at Wabash College and Harvard Business School and built a career as a logistics entrepreneur who transformed a struggling auto parts distributor into Meyer Distributing, employing thousands across the Midwest. He later served on the Jasper school board and in the Indiana House, pushing balanced budgets and workforce training.\n\nElected in 2018, Braun brings spreadsheets to hearings on healthcare pricing, trucking regulations, and conservation funding for hardwood forests.",
    ),
    Senator(
      id: "todd_young",
      name: "Todd Young",
      state: "Indiana",
      biography: "Todd Young was born in Lancaster, Pennsylvania and moved to Carmel, Indiana, where participation in church youth groups and Boy Scouts led him toward the Naval Academy.\n\nHe studied at the U.S. Naval Academy, the University of Chicago Booth School of Business, and Indiana University McKinney School of Law and built a career as a Marine Corps intelligence officer who later worked as a management consultant and congressional staffer before winning a U.S. House seat in 2010. He helped craft the JOBS Act and other entrepreneurship policies.\n\nYoung joined the Senate in 2017 and has since focused on semiconductor incentives, adoption tax credits, and alliances in the Indo-Pacific, drawing on both his military and business background.",
    ),
    Senator(
      id: "chuck_grassley",
      name: "Chuck Grassley",
      state: "Iowa",
      biography: "Chuck Grassley was born in New Hartford, Iowa and grew up working on his parents' diversified farm, a routine that still finds him on a John Deere tractor every harvest season.\n\nHe studied at the University of Northern Iowa and built a career as a state legislator, factory worker, and member of the U.S. House before winning a Senate seat in 1980. His penchant for oversight hearings and annual '99 County' tours earned him the nickname 'the tweeting farmer.'\n\nGrassley is now the Senate's longest-serving Republican and remains deeply involved in judiciary, biofuels, and whistleblower protections, citing farmers and small-town sheriffs at nearly every markup.",
    ),
    Senator(
      id: "joni_ernst",
      name: "Joni Ernst",
      state: "Iowa",
      biography: "Joni Ernst was born in Red Oak, Iowa and grew up on a Montgomery County hog farm where she helped castrate pigs before dawn and sang in the FFA choir after school.\n\nShe studied at Iowa State University and Columbus State University and built a career as an Iowa Army National Guard lieutenant colonel who led convoys in Kuwait and Iraq before serving as county auditor and a state senator. Her 'squeal' ad about cutting pork barrel spending vaulted her onto the national stage.\n\nSince 2015 Ernst has focused on biofuel research, sexual assault prevention in the military, and child care for Guard families, drawing on her service record and life as a single mother.",
    ),
    Senator(
      id: "jerry_moran",
      name: "Jerry Moran",
      state: "Kansas",
      biography: "Jerry Moran was born in Great Bend, Kansas and was raised in the wheat belt, where he learned to drive combines before he could legally drive a car.\n\nHe studied at the University of Kansas and its law school and built a career as a county attorney and state senator who later represented the sprawling First District in the U.S. House, known as 'the Big First'. He logged thousands of miles holding listening sessions in every county each year.\n\nSince 2011 Moran has focused on veterans healthcare in rural areas, aviation manufacturing, and the future of Fort Riley and McConnell Air Force Base.",
    ),
    Senator(
      id: "roger_marshall",
      name: "Roger Marshall",
      state: "Kansas",
      biography: "Roger Marshall was born in El Dorado, Kansas and grew up in Butler County raising 4-H steers and playing high school football before attending Butler Community College.\n\nHe studied at Kansas State University and the University of Kansas School of Medicine and built a career as an obstetrician in Great Bend who delivered more than 5,000 babies and chaired the local Chamber of Commerce before entering politics. His volunteer medical trips to Haiti and Afghanistan shaped his approach to public health.\n\nElected in 2020 after two terms in the House, Marshall stresses food supply chains, telehealth, and border security through the lens of a doctor who kept rural clinics afloat.",
    ),
    Senator(
      id: "mitch_mcconnell",
      name: "Mitch McConnell",
      state: "Kentucky",
      biography: "Mitch McConnell was born in Sheffield, Alabama and survived polio as a toddler before moving to Louisville, where his mother insisted on rigorous physical therapy that restored his ability to walk.\n\nHe studied at the University of Louisville and the University of Kentucky College of Law and built a career as an aide to Senator Marlow Cook, a Jefferson County judge-executive, and eventually a U.S. senator first elected in 1984. He became famous for his mastery of Senate rules and his fundraising prowess for Republican candidates nationwide.\n\nAs the chamber's longest-serving party leader, McConnell wields influence over judicial confirmations, coal community aid, and federal investments in logistics hubs along the Ohio River.",
    ),
    Senator(
      id: "rand_paul",
      name: "Rand Paul",
      state: "Kentucky",
      biography: "Rand Paul was born in Pittsburgh, Pennsylvania and moved with his family to Texas and later Kentucky, where he worked on his father Ron Paul's congressional campaigns.\n\nHe studied at Baylor University and Duke University School of Medicine and built a career as an ophthalmologist in Bowling Green who founded a low-cost eye clinic and performed pro bono surgeries throughout the Bluegrass State. He became a favorite of the Tea Party movement by calling for balanced budgets and civil liberties protections.\n\nElected in 2010, Paul continues to champion audit-the-Fed proposals, criminal justice reform, and a noninterventionist foreign policy rooted in constitutional arguments.",
    ),
    Senator(
      id: "bill_cassidy",
      name: "Bill Cassidy",
      state: "Louisiana",
      biography: "Bill Cassidy was born in Highland Park, Illinois and moved to Baton Rouge as a teenager and spent weekends fishing the Atchafalaya Basin while his parents worked in education and civic service.\n\nHe studied at Louisiana State University for both undergraduate studies and medical school and built a career as a gastroenterologist who co-founded the Greater Baton Rouge Community Clinic and set up makeshift hospitals for Hurricane Katrina evacuees. He later represented Baton Rouge in the state senate and the U.S. House, where he focused on energy policy.\n\nSince 2015 Cassidy has prioritized surprise medical billing reform, carbon-capture research, and coastal restoration projects that protect Louisiana's working coast.",
    ),
    Senator(
      id: "john_kennedy",
      name: "John Kennedy",
      state: "Louisiana",
      biography: "John Kennedy was born in Centreville, Mississippi and grew up in Zachary, Louisiana, showing cattle at county fairs and excelling in debate.\n\nHe studied at Vanderbilt University, the University of Virginia School of Law, and Oxford University and built a career as a tax attorney who became Louisiana's secretary of revenue and later the state's longtime treasurer, famous for his colorful warnings about deficits. He was known for checking every line item in bond prospectuses before approving them.\n\nElected in 2016, Kennedy brings that fiscal hawk persona to federal hearings on flood insurance, crime, and consumer protection, often framing issues with folksy analogies.",
    ),
    Senator(
      id: "susan_collins",
      name: "Susan Collins",
      state: "Maine",
      biography: "Susan Collins was born in Caribou, Maine and grew up as the middle daughter in a family that ran a fifth-generation lumber business and served on the local school board.\n\nShe studied at St. Lawrence University and built a career as a congressional staffer and director of the Small Business Administration's New England regional office before running Maine's Center for Family Business. Her meticulous approach to constituent services led to record-setting bipartisan support back home.\n\nIn the Senate since 1997, Collins is known for swing votes on healthcare and Supreme Court nominees, as well as tireless advocacy for shipbuilding jobs at Bath Iron Works and for icebreaking on the Penobscot River.",
    ),
    Senator(
      id: "angus_king",
      name: "Angus King",
      state: "Maine",
      biography: "Angus King was born in Alexandria, Virginia and spent summer vacations in Maine, falling in love with the coast long before making Brunswick his permanent home.\n\nHe studied at Dartmouth College and the University of Virginia School of Law and built a career as an energy lawyer turned entrepreneur who invested early in cable television systems and later served two terms as Maine's independent governor. As governor he expanded laptop programs for middle schoolers and preserved millions of acres of forestland.\n\nElected as an independent in 2012, King caucuses with Democrats but often plays bridge-builder on cyber security, national parks, and offshore wind development in the Gulf of Maine.",
    ),
    Senator(
      id: "ben_cardin",
      name: "Ben Cardin",
      state: "Maryland",
      biography: "Ben Cardin was born in Baltimore, Maryland and was raised in a family steeped in city politics; his uncle was the longtime speaker of the Maryland House.\n\nHe studied at the University of Pittsburgh and the University of Maryland School of Law and built a career as elected to the Maryland House at age 23, later serving as speaker before winning a seat in the U.S. House, where he specialized in tax law and Social Security. He authored the retirement-savings provisions that still underpin 401(k) portability.\n\nIn the Senate since 2007, Cardin chairs the Small Business Committee and is a leading voice on human rights, water quality in the Chesapeake Bay, and benefits for federal employees in the Baltimore-Washington corridor.",
    ),
    Senator(
      id: "chris_van_hollen",
      name: "Chris Van Hollen",
      state: "Maryland",
      biography: "Chris Van Hollen was born in Karachi, Pakistan and grew up in embassies overseas before his foreign service parents settled in Montgomery County, where he captained the debate team.\n\nHe studied at Swarthmore College, Harvard's Kennedy School, and Georgetown Law and built a career as a policy analyst and state legislator who went on to lead the Democratic Congressional Campaign Committee while serving in the U.S. House. He played a key role designing the 2010 budget deal that averted a government shutdown.\n\nElected in 2016, Van Hollen focuses on space policy at NASA Goddard, metro funding, and sanctions policy, often drawing on his upbringing in Cold War capitals.",
    ),
    Senator(
      id: "elizabeth_warren",
      name: "Elizabeth Warren",
      state: "Massachusetts",
      biography: "Elizabeth Warren was born in Oklahoma City, Oklahoma and grew up on Route 66 in a family that nearly lost its home after her father's heart attack, an event that cemented her interest in bankruptcy law.\n\nShe studied at the University of Houston and Rutgers Law School and built a career as a law professor at the University of Texas, the University of Pennsylvania, and Harvard whose research on middle-class debt helped create the Consumer Financial Protection Bureau. She chaired the Congressional Oversight Panel during the Troubled Asset Relief Program.\n\nElected in 2012, Warren presses for antitrust enforcement, affordable childcare, and student debt relief, often backing her arguments with binders full of footnotes.",
    ),
    Senator(
      id: "ed_markey",
      name: "Ed Markey",
      state: "Massachusetts",
      biography: "Ed Markey was born in Malden, Massachusetts and was the son of a milkman and grew up in a triple-decker where he shared a bedroom with his brothers until college.\n\nHe studied at Boston College and Boston College Law School and built a career as a state representative who kept his law books in an ice cream truck while studying for the bar, then served 37 years in the U.S. House focusing on telecom policy and environmental protection. He co-authored the original fuel-economy standards and the Waxman-Markey climate bill.\n\nServing in the Senate since 2013, Markey promotes the Green New Deal, children's online privacy, and funding for the MBTA.",
    ),
    Senator(
      id: "debbie_stabenow",
      name: "Debbie Stabenow",
      state: "Michigan",
      biography: "Debbie Stabenow was born in Gladwin, Michigan and grew up playing piano in church and organizing 4-H meetings while her parents ran a small hardware store.\n\nShe studied at Michigan State University and built a career as a social worker and county commissioner who later served in the Michigan House and Senate, then in the U.S. House. She ran the statewide mental health system in Ingham County, emphasizing community clinics.\n\nSince 2001 Stabenow has been a leading voice on the farm bill, Great Lakes cleanup, and advanced battery manufacturing, helping Michigan factories retool for electric vehicles.",
    ),
    Senator(
      id: "gary_peters",
      name: "Gary Peters",
      state: "Michigan",
      biography: "Gary Peters was born in Pontiac, Michigan and was raised by a union teacher and a nurse's aide, delivering the Detroit Free Press before dawn.\n\nHe studied at Alma College, the University of Detroit Mercy School of Law, and the College of Naval Command and Staff and built a career as worked in finance, served in the Navy Reserve for more than 20 years, and held state senate and statewide offices before winning a U.S. House seat. He was Michigan's Lottery Commissioner, modernizing its technology.\n\nElected in 2014, Peters leads the Homeland Security Committee, where he tackles supply-chain resilience, shoreline restoration, and cybersecurity threats to automakers.",
    ),
    Senator(
      id: "amy_klobuchar",
      name: "Amy Klobuchar",
      state: "Minnesota",
      biography: "Amy Klobuchar was born in Plymouth, Minnesota and is the daughter of a journalist and a second-grade teacher, and learned early to combine curiosity with pragmatism while canvassing for school levies.\n\nShe studied at Yale University and the University of Chicago Law School and built a career as a corporate attorney who became Hennepin County attorney, modernizing the office's victim services and technology. She built a reputation for accountability after the I-35W bridge collapse, coordinating engineers and first responders.\n\nIn the Senate since 2007, Klobuchar focuses on competition policy, rural broadband, and election security, often citing town meetings in Iron Range gyms to explain bipartisan progress.",
    ),
    Senator(
      id: "tina_smith",
      name: "Tina Smith",
      state: "Minnesota",
      biography: "Tina Smith was born in Albuquerque, New Mexico and moved frequently with her Air Force family before settling in Minnesota, where she worked on college-catalyzed community service projects.\n\nShe studied at Stanford University and the Tuck School of Business at Dartmouth and built a career as a marketing professional who became chief of staff to Minneapolis Mayor R.T. Rybak and Governor Mark Dayton, then served as lieutenant governor. She helped negotiate the Vikings stadium package and led early childhood initiatives.\n\nAppointed in 2018 and then elected twice, Smith champions mental health parity, reproductive freedom, and strengthening the bio-based economy from Rochester to Duluth.",
    ),
    Senator(
      id: "cindy_hyde_smith",
      name: "Cindy Hyde-Smith",
      state: "Mississippi",
      biography: "Cindy Hyde-Smith was born in Brookhaven, Mississippi and showed prize cattle in local fairs and learned the rhythms of ranch life on her family's farm in Lincoln County.\n\nShe studied at Copiah-Lincoln Community College and the University of Southern Mississippi and built a career as a livestock auctioneer and state senator who later became Mississippi's commissioner of agriculture and commerce. She modernized disease-tracking systems for poultry and cattle, the state's biggest exports.\n\nAppointed in 2018 and elected later that year, Hyde-Smith focuses on crop insurance, the Gulf Coast shipyard workforce, and expanding rural clinics.",
    ),
    Senator(
      id: "roger_wicker",
      name: "Roger Wicker",
      state: "Mississippi",
      biography: "Roger Wicker was born in Pontotoc, Mississippi and grew up in a judge's household steeped in civic duty and joined the Air Force ROTC at Ole Miss.\n\nHe studied at the University of Mississippi for both undergraduate and law degrees and built a career as an Air Force judge advocate who later served in the Mississippi Senate and then the U.S. House beginning in 1994. He chaired the House Republican Policy Committee while championing military installations on the Gulf Coast.\n\nIn the Senate since 2007, Wicker now chairs the Commerce Committee's seas subpanel, pushing for shipbuilding contracts, coastal restoration, and broadband access along the Delta.",
    ),
    Senator(
      id: "josh_hawley",
      name: "Josh Hawley",
      state: "Missouri",
      biography: "Josh Hawley was born in Springdale, Arkansas and moved to Lexington, Missouri, where he devoured history books and edited the high school newspaper.\n\nHe studied at Stanford University and Yale Law School and built a career as a Supreme Court clerk for Chief Justice John Roberts, constitutional lawyer, and Missouri attorney general. He argued multiple cases defending state laws on religious liberty and consumer privacy.\n\nElected in 2018, Hawley focuses on Big Tech regulation, supply-chain nationalism, and the rights of gig economy workers, all while emphasizing a populist brand of conservatism.",
    ),
    Senator(
      id: "eric_schmitt",
      name: "Eric Schmitt",
      state: "Missouri",
      biography: "Eric Schmitt was born in Bridgeton, Missouri and was raised by a union electrician and a preschool teacher, playing defensive tackle at De Smet Jesuit High School.\n\nHe studied at Truman State University and Saint Louis University School of Law and built a career as a private attorney who served as an alderman, state senator, state treasurer, and then Missouri attorney general. He spearheaded lawsuits on behalf of parents of children with special needs, inspired by his own son's autism diagnosis.\n\nSchmitt won a Senate seat in 2022 and now concentrates on energy policy, parental rights, and reshoring advanced manufacturing in the St. Louis corridor.",
    ),
    Senator(
      id: "jon_tester",
      name: "Jon Tester",
      state: "Montana",
      biography: "Jon Tester was born in Havre, Montana and is a third-generation farmer who still grows organic wheat and lentils near Big Sandy despite losing three fingers in a childhood meat-grinder accident.\n\nHe studied at the University of Great Falls and built a career as a music teacher and school board member who served in the Montana Senate, rising to president before winning a U.S. Senate seat in 2006. He helped write the state's constitutional ban on dark money.\n\nTester chairs the Veterans Affairs Committee and fights for rural broadband and irrigation projects, often reminding colleagues that he flies home each weekend to fix tractors on the family farm.",
    ),
    Senator(
      id: "steve_daines",
      name: "Steve Daines",
      state: "Montana",
      biography: "Steve Daines was born in Van Hook, North Dakota and moved to Bozeman as a child, where he joined Scouts, hunted elk, and helped his parents run a small surveying business.\n\nHe studied at Montana State University with a degree in chemical engineering and built a career as spent 13 years as a Procter & Gamble executive launching factories in Asia before returning to Montana to work for RightNow Technologies, a Bozeman cloud company. He also served as Montana chair for the American Red Cross during wildfire seasons.\n\nElected to the Senate in 2014, Daines focuses on forest management, semiconductor incentives in the Mountain West, and securing northern border crossings.",
    ),
    Senator(
      id: "deb_fischer",
      name: "Deb Fischer",
      state: "Nebraska",
      biography: "Deb Fischer was born in Lincoln, Nebraska and spent summers fixing fence on her family's Sandhills ranch and learning parliamentary procedure through 4-H.\n\nShe studied at the University of Nebraska–Lincoln and built a career as a rancher who served on the local school board for 18 years before winning a seat in the unicameral Nebraska Legislature. She chaired the Transportation and Telecommunications Committee, securing funding for expressways.\n\nIn the Senate since 2013, Fischer champions precision agriculture, military family housing at Offutt Air Force Base, and pragmatic infrastructure budgeting.",
    ),
    Senator(
      id: "pete_ricketts",
      name: "Pete Ricketts",
      state: "Nebraska",
      biography: "Pete Ricketts was born in Nebraska City, Nebraska and grew up in a family that founded TD Ameritrade, learning investment basics at the dinner table while also volunteering at Boys Town.\n\nHe studied at the University of Chicago for both undergraduate and MBA degrees and built a career as helped build TD Ameritrade into a national brokerage, then served two terms as Nebraska's governor from 2015 to 2023. His administration emphasized property tax cuts, flood recovery, and public-private partnerships for workforce housing.\n\nAppointed in 2023 to succeed Ben Sasse, Ricketts now works on trade, rail chokepoints, and protecting the meatpacking supply chain.",
    ),
    Senator(
      id: "catherine_cortez_masto",
      name: "Catherine Cortez Masto",
      state: "Nevada",
      biography: "Catherine Cortez Masto was born in Las Vegas, Nevada and is the granddaughter of a Mexican immigrant who built one of the city's first grocery stores, and she watched the valley grow from a dusty outpost to a global tourism hub.\n\nShe studied at the University of Nevada, Reno and Gonzaga University School of Law and built a career as served as chief of staff to Governor Bob Miller, federal prosecutor, and later Nevada's attorney general. She prosecuted mortgage fraud during the Great Recession and established the state's first senior protection unit.\n\nElected in 2016, Cortez Masto focuses on drought resilience, tribal broadband, and consumer protections for service workers on the Strip.",
    ),
    Senator(
      id: "jacky_rosen",
      name: "Jacky Rosen",
      state: "Nevada",
      biography: "Jacky Rosen was born in Chicago, Illinois and was the first in her family to attend college and paid tuition by waiting tables and writing software on the side.\n\nShe studied at the University of Minnesota and built a career as a computer programmer for major casinos who later became president of Congregation Ner Tamid in Henderson. She launched a food pantry and interfaith partnerships during the Great Recession.\n\nAfter one term in the U.S. House she flipped a Senate seat in 2018 and now champions STEM apprenticeships, aviation innovation at Harry Reid International Airport, and support for caregivers of veterans.",
    ),
    Senator(
      id: "jeanne_shaheen",
      name: "Jeanne Shaheen",
      state: "New Hampshire",
      biography: "Jeanne Shaheen was born in St. Charles, Missouri and moved frequently as the daughter of an Army engineer before settling in New Hampshire to teach high school and coach a girls' basketball team.\n\nShe studied at Shippensburg University and the University of Mississippi and built a career as ran a small jewelry business, served in the state senate, and became the first woman elected governor of New Hampshire. Her administration expanded kindergarten, created the Job Training Fund, and navigated the aftermath of the 9/11 attacks.\n\nIn the Senate since 2009, Shaheen works on small-business lending, energy efficiency for cold climates, and bipartisan diplomacy through the Foreign Relations Committee.",
    ),
    Senator(
      id: "maggie_hassan",
      name: "Maggie Hassan",
      state: "New Hampshire",
      biography: "Maggie Hassan was born in Boston, Massachusetts and is the daughter of an Army research physician who instilled a commitment to public service and problem-solving.\n\nShe studied at Brown University and Northeastern University School of Law and built a career as served as New Hampshire's governor, where she expanded Medicaid and negotiated a commuter rail agreement, after previously working as an attorney and state senator. Her advocacy for people with disabilities is informed by raising a son with cerebral palsy.\n\nElected to the Senate in 2016, Hassan focuses on cybersecurity workforce training, fentanyl interdiction, and lowering energy costs for New England families.",
    ),
    Senator(
      id: "bob_menendez",
      name: "Bob Menendez",
      state: "New Jersey",
      biography: "Bob Menendez was born in New York City, New York and was raised in Union City by Cuban immigrants who worked sewing jobs and insisted he take nightly public speaking classes.\n\nHe studied at Saint Peter's University and Rutgers Law School and built a career as became the youngest mayor in the city at 32, later serving in the New Jersey legislature and the U.S. House, where he focused on housing and transportation. He chaired the House Democratic Caucus and negotiated multiple Hudson River tunnel agreements.\n\nAppointed in 2006 and subsequently elected, Menendez often leads on Latin American policy, port security, and chemical plant safety, citing his Hudson County roots.",
    ),
    Senator(
      id: "cory_booker",
      name: "Cory Booker",
      state: "New Jersey",
      biography: "Cory Booker was born in Washington, D.C. and grew up in Harrington Park, New Jersey, where his parents broke color barriers as IBM executives and taught their son to challenge housing discrimination.\n\nHe studied at Stanford University, Oxford University as a Rhodes Scholar, and Yale Law School and built a career as a tenants' rights attorney who moved into Newark public housing, served on the city council, and was elected mayor, drawing national attention for hands-on crisis response. He famously shoveled residents' driveways during blizzards and rescued a neighbor from a burning home.\n\nSince 2013 Booker has focused on criminal justice reform, community finance, and nutrition policy, bringing Newark stories into every committee room.",
    ),
    Senator(
      id: "martin_heinrich",
      name: "Martin Heinrich",
      state: "New Mexico",
      biography: "Martin Heinrich was born in Fallon, Nevada and was raised in Silver City, New Mexico, where Boy Scout hikes through the Gila Wilderness sparked a lifelong passion for public lands.\n\nHe studied at the University of Missouri with a mechanical engineering degree and built a career as worked as an engineer at Phillips Laboratories, founded a solar company, and served on the Albuquerque City Council before winning a U.S. House seat. He helped create the Bosque School's environmental program and served as New Mexico's natural resources trustee.\n\nIn the Senate since 2013, Heinrich champions outdoor recreation economies, national labs, and bipartisan privacy reforms for emerging technology.",
    ),
    Senator(
      id: "ben_ray_lujan",
      name: "Ben Ray Lujan",
      state: "New Mexico",
      biography: "Ben Ray Lujan was born in Santa Fe, New Mexico and is the son of longtime state House Speaker Ben Lujan and grew up near the Pojoaque Valley attending pueblo dances and rodeos.\n\nHe studied at the University of New Mexico and built a career as held posts in the state's cultural affairs and public regulation commissions before winning a U.S. House seat in 2008, eventually chairing the Democratic Congressional Campaign Committee. He helped expand broadband to rural pueblos and launched the 'Young Guns' recruitment program.\n\nElected in 2020, Lujan now focuses on wildfire recovery, microelectronics research at Sandia and Los Alamos, and healthcare access for tribal communities.",
    ),
    Senator(
      id: "chuck_schumer",
      name: "Chuck Schumer",
      state: "New York",
      biography: "Chuck Schumer was born in Brooklyn, New York and is the son of a pest exterminator and a homemaker, and he carried flashcards on the subway to prepare for debate tournaments at Madison High School.\n\nHe studied at Harvard College and Harvard Law School and built a career as elected to the New York State Assembly at 23, then to the U.S. House, where he chaired the Judiciary Subcommittee on Crime and authored the Brady Bill. He built a reputation for Sunday press conferences on every corner of New York City.\n\nIn the Senate since 1999 and now majority leader, Schumer works on semiconductor incentives, transit megaprojects, and judicial confirmations, all while holding fast to his Brooklyn roots.",
    ),
    Senator(
      id: "kirsten_gillibrand",
      name: "Kirsten Gillibrand",
      state: "New York",
      biography: "Kirsten Gillibrand was born in Albany, New York and grew up in a politically active family—her grandmother organized secretary unions at the state Capitol—instilling a penchant for coalition building.\n\nShe studied at Dartmouth College and UCLA School of Law and built a career as a corporate attorney who served as special counsel at HUD before winning a rural upstate congressional seat in 2006. She launched the first congressional transparency database of earmarks and meetings.\n\nAppointed in 2009 and elected statewide since, Gillibrand leads on military sexual assault reform, paid family leave, and PFAS cleanup around upstate air bases.",
    ),
    Senator(
      id: "thom_tillis",
      name: "Thom Tillis",
      state: "North Carolina",
      biography: "Thom Tillis was born in Jacksonville, Florida and was raised in a working-class family that moved frequently, forcing him to attend five high schools before settling in Nashville, Tennessee.\n\nHe studied at the University of Maryland Global Campus while working full time at IBM and built a career as a management consultant at PricewaterhouseCoopers and IBM who later won a seat in the North Carolina House, rising to speaker. He led major tort, tax, and education overhauls in Raleigh.\n\nSince 2015 Tillis has focused on immigration modernization, veteran suicide prevention at Fort Bragg, and semiconductor investments in the Research Triangle.",
    ),
    Senator(
      id: "ted_budd",
      name: "Ted Budd",
      state: "North Carolina",
      biography: "Ted Budd was born in Winston-Salem, North Carolina and split time between a small family farm and a garden center, learning to repair tractors before he could drive.\n\nHe studied at Appalachian State University, Dallas Theological Seminary for a master's in business, and Wake Forest University School of Business and built a career as owns a gun store and range and ran the Budd Group, his family's facility-services company, before winning a U.S. House seat in 2016. He helped shepherd bipartisan financial technology legislation through the House.\n\nBudd joined the Senate in 2023 and now emphasizes supply-chain security, rural broadband, and protecting North Carolina's military installations from encroachment.",
    ),
    Senator(
      id: "john_hoeven",
      name: "John Hoeven",
      state: "North Dakota",
      biography: "John Hoeven was born in Bismarck, North Dakota and is the son of a banker, and he worked summers at community pools before heading to Dartmouth.\n\nHe studied at Dartmouth College and Northwestern University's Kellogg School of Management and built a career as headed the state's largest community bank before serving a decade as North Dakota's governor, overseeing the Bakken shale boom. He launched the North Dakota Medora Foundation and championed value-added agriculture.\n\nSince 2011 Hoeven has focused on farm insurance, tribal partnerships, and veterans clinics for the rural High Plains.",
    ),
    Senator(
      id: "kevin_cramer",
      name: "Kevin Cramer",
      state: "North Dakota",
      biography: "Kevin Cramer was born in Rolette, North Dakota and grew up in a railroad family, bagging groceries and delivering papers in Kindred.\n\nHe studied at Concordia College and the University of Mary and built a career as served as state tourism director, economic development director, and Public Service Commissioner before winning a U.S. House seat in 2012. He oversaw pipeline safety and telecom expansion during the oil boom.\n\nElected to the Senate in 2018, Cramer advocates for carbon capture, national defense missions at Grand Forks, and pro-life policies.",
    ),
    Senator(
      id: "sherrod_brown",
      name: "Sherrod Brown",
      state: "Ohio",
      biography: "Sherrod Brown was born in Mansfield, Ohio and is the son of a small-town doctor and a mother who led the local PTA, and he wore a union-made suit to high school graduation.\n\nHe studied at Ohio State University for undergraduate and master's degrees and later the John F. Kennedy School of Government and built a career as served in the Ohio House, as Ohio's secretary of state, and then 14 years in the U.S. House representing the industrial Mahoning Valley. He became known for his annual manufacturing report cards and his raspy-voiced floor speeches defending workers.\n\nSince 2007 Brown has championed the CHIPS and Science Act, pension relief for Teamsters, and rail safety reforms after hazardous derailments.",
    ),
    Senator(
      id: "jd_vance",
      name: "JD Vance",
      state: "Ohio",
      biography: "JD Vance was born in Middletown, Ohio and was raised by his grandparents amid factory layoffs, a story he chronicled in his memoir 'Hillbilly Elegy'.\n\nHe studied at Ohio State University and Yale Law School and built a career as a Marine Corps public affairs specialist who deployed to Iraq, later working in venture capital with Steve Case before launching a seed fund for Midwest startups. He founded 'Our Ohio Renewal' to fight opioid addiction in Appalachia.\n\nElected in 2022, Vance now focuses on rail safety, reshoring advanced manufacturing, and limiting American involvement in foreign wars without clear objectives.",
    ),
    Senator(
      id: "james_lankford",
      name: "James Lankford",
      state: "Oklahoma",
      biography: "James Lankford was born in Dallas, Texas and spent summers at Falls Creek Baptist Camp in Oklahoma, eventually directing the camp for teenagers from all 77 counties.\n\nHe studied at the University of Texas and Southwestern Baptist Theological Seminary and built a career as served as director of Falls Creek youth camp for 13 years before winning a U.S. House seat in 2010. He became known for budget watchdog reports that cataloged federal waste.\n\nSince 2015 Lankford has led bipartisan work on government transparency, tribal sovereignty, and the modernization of the IRS customer service model.",
    ),
    Senator(
      id: "markwayne_mullin",
      name: "Markwayne Mullin",
      state: "Oklahoma",
      biography: "Markwayne Mullin was born in Tulsa, Oklahoma and was raised on a ranch near Westville, helping run the family plumbing company after his father's illness.\n\nHe studied at Oklahoma State University Institute of Technology and built a career as expanded Mullin Plumbing into multiple businesses and became known as a champion wrestler before winning a U.S. House seat in 2012. He is one of the few enrolled members of a federally recognized tribe (Cherokee Nation) to serve in Congress.\n\nElected in 2022, Mullin advocates for tribal sovereignty, domestic energy production, and skilled trade education, often bringing his work boots to committee hearings.",
    ),
    Senator(
      id: "ron_wyden",
      name: "Ron Wyden",
      state: "Oregon",
      biography: "Ron Wyden was born in Wichita, Kansas and moved to California as a child, where his Holocaust-survivor parents encouraged him to start a basketball league for low-income kids.\n\nHe studied at the University of California, Santa Barbara and Stanford University, followed by the University of Oregon School of Law and built a career as co-founded the Oregon Gray Panthers, a seniors advocacy group, before serving in the U.S. House from 1981 to 1996. He became known for 'Oregon Trail' town halls, promising to visit each county every year.\n\nIn the Senate Wyden chairs the Finance Committee and champions privacy rights, timber restoration, and clean energy tax credits.",
    ),
    Senator(
      id: "jeff_merkley",
      name: "Jeff Merkley",
      state: "Oregon",
      biography: "Jeff Merkley was born in Myrtle Creek, Oregon and spent part of his childhood in a mobile home park while his father worked as a mechanic, instilling empathy for families on the edge.\n\nHe studied at Stanford University and Princeton University's Woodrow Wilson School and built a career as an energy analyst at the Congressional Budget Office who returned to Oregon to serve in the state legislature, becoming speaker of the House during the Great Recession. He expanded affordable housing trust funds and cracked down on payday lending.\n\nSince 2009 Merkley has pressed for climate justice, reforming the Senate filibuster, and supporting refugees who resettle in the Pacific Northwest.",
    ),
    Senator(
      id: "bob_casey",
      name: "Bob Casey Jr.",
      state: "Pennsylvania",
      biography: "Bob Casey Jr. was born in Scranton, Pennsylvania and is the son of the late Governor Bob Casey Sr., and learned retail politics by shaking hands outside Lackawanna County churches.\n\nHe studied at the College of the Holy Cross and Catholic University's Columbus School of Law and built a career as served as Pennsylvania's auditor general and treasurer, focusing on nursing home inspections and college savings programs. He created the state's first fraud tip line for Medicaid abuse.\n\nElected in 2006, Casey now concentrates on child tax credits, autism research, and the health of workers who build the Scranton Army Ammunition Plant.",
    ),
    Senator(
      id: "john_fetterman",
      name: "John Fetterman",
      state: "Pennsylvania",
      biography: "John Fetterman was born in Reading, Pennsylvania and was raised in York by parents who emphasized service despite comfortable means, a perspective that deepened when a close friend died in a car accident.\n\nHe studied at Albright College, the University of Connecticut, and Harvard's Kennedy School and built a career as served as mayor of Braddock for 13 years, launching urban gardens, legal clinics, and art initiatives to breathe new life into the steel town. As lieutenant governor he chaired the Board of Pardons and championed criminal justice reform.\n\nFetterman won a 2022 Senate race while recovering from a stroke, and he now focuses on rail safety, the steel supply chain, and mental health care access.",
    ),
    Senator(
      id: "jack_reed",
      name: "Jack Reed",
      state: "Rhode Island",
      biography: "Jack Reed was born in Cranston, Rhode Island and was the son of a school janitor and a seamstress, and he helped care for younger cousins in the close-knit neighborhood.\n\nHe studied at the U.S. Military Academy at West Point, Harvard's Kennedy School, and Harvard Law School and built a career as served as an Army Ranger and paratrooper, taught at West Point, and later became a state senator and U.S. representative. He specialized in housing finance at a Providence law firm before entering Congress.\n\nIn the Senate since 1997, Reed chairs the Armed Services Committee and consistently advocates for the Navy's undersea fleet and for affordable housing along Narragansett Bay.",
    ),
    Senator(
      id: "sheldon_whitehouse",
      name: "Sheldon Whitehouse",
      state: "Rhode Island",
      biography: "Sheldon Whitehouse was born in New York City, New York and lived overseas while his father served as a diplomat, eventually returning to Rhode Island for high school.\n\nHe studied at Yale University and the University of Virginia School of Law and built a career as was Rhode Island's U.S. attorney and attorney general, notable for prosecuting public corruption and corporate polluters. He negotiated the Master Settlement Agreement with tobacco companies.\n\nSince 2007 Whitehouse has focused on climate accountability, Supreme Court ethics, and protecting the state's coastal fisheries from warming waters.",
    ),
    Senator(
      id: "lindsey_graham",
      name: "Lindsey Graham",
      state: "South Carolina",
      biography: "Lindsey Graham was born in Central, South Carolina and was the first in his family to attend college, supporting his parents' pool hall while they battled illness.\n\nHe studied at the University of South Carolina for both undergraduate and law degrees and built a career as served as an Air Force and Air National Guard judge advocate, then as a state representative and U.S. House member beginning in 1994. He deployed to Iraq and Afghanistan as a reservist even while serving in Congress.\n\nIn the Senate since 2003, Graham works on military readiness at bases like Fort Jackson and Parris Island, while also crafting bipartisan criminal justice reforms and judiciary legislation.",
    ),
    Senator(
      id: "tim_scott",
      name: "Tim Scott",
      state: "South Carolina",
      biography: "Tim Scott was born in North Charleston, South Carolina and was raised by a single mother who worked double shifts as a nurse's aide, and a Chick-fil-A mentor steered him toward business classes.\n\nHe studied at Charleston Southern University and built a career as launched an insurance and real estate company, served on the Charleston County Council, in the state house, and then in the U.S. House. He authored 'Opportunity Zone' policies to spur investment in distressed neighborhoods.\n\nAppointed in 2013 and later elected statewide, Scott focuses on workforce apprenticeships, policing reform, and flood mitigation along the Lowcountry coast.",
    ),
    Senator(
      id: "john_thune",
      name: "John Thune",
      state: "South Dakota",
      biography: "John Thune was born in Pierre, South Dakota and was the son of a World War II fighter pilot and grew up playing basketball and selling popcorn at the local theater.\n\nHe studied at Biola University and the University of South Dakota and built a career as worked in the late Senator James Abdnor's office, led the South Dakota Railroad Administration, and served in the U.S. House from 1996 to 2002. He later headed the South Dakota Municipal League, focusing on water projects.\n\nElected to the Senate in 2004, Thune now serves as Republican whip and concentrates on rail policy, Ellsworth Air Force Base missions, and rural broadband.",
    ),
    Senator(
      id: "mike_rounds",
      name: "Mike Rounds",
      state: "South Dakota",
      biography: "Mike Rounds was born in Huron, South Dakota and was the eldest of eleven children in a family that ran an insurance agency and taught all the kids to work the phones.\n\nHe studied at South Dakota State University and built a career as co-owned Fischer Rounds Insurance and served in the state senate for a decade before becoming governor from 2003 to 2011. His governorship emphasized biotech recruitment and rebuilding after the 2011 Missouri River floods.\n\nSince 2015 Rounds has focused on banking innovation, tribal housing, and the modernization of the Air National Guard's 114th Fighter Wing.",
    ),
    Senator(
      id: "marsha_blackburn",
      name: "Marsha Blackburn",
      state: "Tennessee",
      biography: "Marsha Blackburn was born in Laurel, Mississippi and was raised in a small delta town before moving to Tennessee for college, selling books door to door to pay tuition.\n\nShe studied at Mississippi State University and built a career as a marketing executive for the Castner Knott retail chain who later served in the Tennessee Senate and the U.S. House. She organized a statewide grassroots movement against a proposed state income tax.\n\nElected in 2018, Blackburn focuses on intellectual property enforcement in the music industry, broadband for Appalachia, and countering Chinese influence in supply chains.",
    ),
    Senator(
      id: "bill_hagerty",
      name: "Bill Hagerty",
      state: "Tennessee",
      biography: "Bill Hagerty was born in Gallatin, Tennessee and grew up on a cattle farm in Sumner County before pursuing finance in Nashville.\n\nHe studied at Vanderbilt University for both undergraduate and law degrees and built a career as worked in private equity, served as Tennessee's commissioner of economic development, and was U.S. ambassador to Japan from 2017 to 2019. He led recruitment of auto plants and tech campuses to the Volunteer State.\n\nElected in 2020, Hagerty now concentrates on Indo-Pacific alliances, automotive trade, and keeping Tennessee a magnet for investment.",
    ),
    Senator(
      id: "john_cornyn",
      name: "John Cornyn",
      state: "Texas",
      biography: "John Cornyn was born in Houston, Texas and moved frequently as the son of an Air Force pilot, attending high school on military bases in Japan and South Carolina before returning to San Antonio.\n\nHe studied at Trinity University, St. Mary's University School of Law, and the University of Virginia School of Law and built a career as practiced law in San Antonio, served as a state district judge, Texas Supreme Court justice, and Texas attorney general. As attorney general he created the state's first internet crimes against children task force.\n\nIn the Senate since 2002 and a former majority whip, Cornyn focuses on border modernization, semiconductor incentives in Texas, and mental health partnerships with law enforcement.",
    ),
    Senator(
      id: "ted_cruz",
      name: "Ted Cruz",
      state: "Texas",
      biography: "Ted Cruz was born in Calgary, Alberta and moved to Houston as a child, where his father ran an oilfield service business and his mother wrote computer software.\n\nHe studied at Princeton University and Harvard Law School and built a career as clerked for Chief Justice William Rehnquist, served as Texas solicitor general, and argued nine cases before the U.S. Supreme Court. He became a national Tea Party figure during the Affordable Care Act debates.\n\nSince 2013 Cruz has focused on energy independence, limiting federal regulation, and strengthening missile defense, often citing Texas's role as a space and energy leader.",
    ),
    Senator(
      id: "mike_lee",
      name: "Mike Lee",
      state: "Utah",
      biography: "Mike Lee was born in Mesa, Arizona and was raised in Provo, Utah, where his father served as solicitor general and instilled a love of constitutional history.\n\nHe studied at Brigham Young University for both undergraduate and law degrees and built a career as clerked for Justice Samuel Alito, worked as an assistant U.S. attorney, and served as general counsel to Utah Governor Jon Huntsman. He later became a prominent litigator in energy and technology cases.\n\nElected in 2010, Lee is known for constitutional originalism, reforms to the Antiquities Act, and bipartisan bills on rail safety and tech competition.",
    ),
    Senator(
      id: "mitt_romney",
      name: "Mitt Romney",
      state: "Utah",
      biography: "Mitt Romney was born in Detroit, Michigan and is the son of auto executive and Michigan Governor George Romney, and spent part of his youth in Bloomfield Hills before serving a Mormon mission in France.\n\nHe studied at Brigham Young University and the joint JD/MBA program at Harvard and built a career as co-founded Bain Capital, rescued the 2002 Salt Lake City Olympics from financial crisis, and served as governor of Massachusetts. His healthcare reforms in Massachusetts inspired elements of the Affordable Care Act.\n\nElected in 2018, Romney focuses on fiscal responsibility, Ukraine aid, and bipartisan rules changes that strengthen the Senate as an institution.",
    ),
    Senator(
      id: "bernie_sanders",
      name: "Bernie Sanders",
      state: "Vermont",
      biography: "Bernie Sanders was born in Brooklyn, New York and grew up in a rent-controlled apartment, the son of a paint salesman who fled Nazi-occupied Poland.\n\nHe studied at the University of Chicago and built a career as moved to Vermont as part of the back-to-the-land movement, worked as a carpenter and film maker, and was elected mayor of Burlington in 1981 before serving in the U.S. House. He built the Burlington waterfront bike path and launched one of the nation's first community-trust funds for small businesses.\n\nIn the Senate since 2007, Sanders caucuses with Democrats but remains an independent voice for Medicare for All, labor rights, and climate investment.",
    ),
    Senator(
      id: "peter_welch",
      name: "Peter Welch",
      state: "Vermont",
      biography: "Peter Welch was born in Springfield, Massachusetts and moved to Vermont after college, working construction jobs and volunteering for legal aid clients.\n\nHe studied at the College of the Holy Cross and the University of California, Berkeley School of Law and built a career as served as a public defender, state senator, and president pro tempore of the Vermont Senate before winning a U.S. House seat in 2006. He helped broker Vermont's landmark civil unions legislation.\n\nElected to the Senate in 2022, Welch focuses on broadband for rural valleys, insulin price caps, and support for dairy farmers navigating volatile markets.",
    ),
    Senator(
      id: "mark_warner",
      name: "Mark Warner",
      state: "Virginia",
      biography: "Mark Warner was born in Indianapolis, Indiana and grew up in a middle-class family that moved to Connecticut, where he was the first in his family to finish college.\n\nHe studied at George Washington University and Harvard Law School and built a career as a venture capitalist who invested early in wireless spectrum and helped build Nextel, later serving as Virginia's governor from 2002 to 2006. As governor he closed a massive budget shortfall while expanding broadband to rural Appalachia.\n\nIn the Senate since 2009, Warner co-chairs the Senate Cybersecurity Caucus and brokers bipartisan deals on infrastructure finance and workforce retraining.",
    ),
    Senator(
      id: "tim_kaine",
      name: "Tim Kaine",
      state: "Virginia",
      biography: "Tim Kaine was born in St. Paul, Minnesota and spent a year as a Jesuit missionary in Honduras while in law school, cementing his commitment to service and fluent Spanish.\n\nHe studied at the University of Missouri and Harvard Law School and built a career as a civil rights lawyer who served as mayor of Richmond, lieutenant governor, governor, and vice-presidential nominee in 2016. He expanded pre-K and the Virginia Community College System's transfer grants.\n\nSince 2013 Kaine has concentrated on military family housing in Hampton Roads, war powers reform, and affordable housing around the Washington Metro.",
    ),
    Senator(
      id: "patty_murray",
      name: "Patty Murray",
      state: "Washington",
      biography: "Patty Murray was born in Bothell, Washington and is the daughter of a World War II veteran who ran a family lumber company before falling ill, forcing her mother back to school to become an accountant.\n\nShe studied at Washington State University and built a career as taught preschool, organized PTA campaigns, and served on the Shoreline School Board before winning seats in the Washington State Senate and then the U.S. Senate in 1992. Dubbed 'the mom in tennis shoes,' she blocked repeated attempts to cut education for disabled children.\n\nMurray is now the Senate president pro tempore and chairs the Appropriations Committee, focusing on childcare, veterans' hospitals, and salmon recovery across the Pacific Northwest.",
    ),
    Senator(
      id: "maria_cantwell",
      name: "Maria Cantwell",
      state: "Washington",
      biography: "Maria Cantwell was born in Indianapolis, Indiana and moved to Ohio as a child, helping in her parents' ice cream shop before volunteering for local fair-housing campaigns.\n\nShe studied at Miami University in Ohio and built a career as served in the Washington House, the U.S. House, and as an executive at streaming pioneer RealNetworks before returning to public service. She helped bring the Seattle Mariners ballpark deal across the finish line and defended the Hanford cleanup budget.\n\nElected in 2000, Cantwell is a leader on aviation safety, net neutrality, and fuel economy standards that keep Boeing, Amazon, and rural cooperatives thriving together.",
    ),
    Senator(
      id: "joe_manchin",
      name: "Joe Manchin",
      state: "West Virginia",
      biography: "Joe Manchin was born in Farmington, West Virginia and is the grandson of a grocery store owner known as 'Papa Joe,' and he grew up delivering coal company checks around Marion County.\n\nHe studied at West Virginia University and built a career as started a coal brokerage, served in the state House and Senate, and became secretary of state before winning the governorship in 2004. He guided West Virginia through the Sago Mine disaster and launched the PROMISE scholarship.\n\nAppointed to the Senate in 2010 and repeatedly reelected, Manchin pushes for energy compromise packages, prescription drug savings, and broadband for Appalachian hollers.",
    ),
    Senator(
      id: "shelley_moore_capito",
      name: "Shelley Moore Capito",
      state: "West Virginia",
      biography: "Shelley Moore Capito was born in Glen Dale, West Virginia and is the daughter of former Governor Arch Moore and spent childhood weekends at high school football games and union picnics across the state.\n\nShe studied at Duke University and the University of Virginia and built a career as worked as a college career counselor and in community outreach before serving in the West Virginia House and then the U.S. House for 14 years. She built the bipartisan Congressional Caucus for Women's Issues.\n\nSince 2015 Capito has prioritized broadband deployment, opioid treatment resources, and transportation funding along Corridor H.",
    ),
    Senator(
      id: "tammy_baldwin",
      name: "Tammy Baldwin",
      state: "Wisconsin",
      biography: "Tammy Baldwin was born in Madison, Wisconsin and was raised by her grandparents after her teenage mother faced mental health struggles, and she spent weeks in the hospital battling a childhood virus that left her with a preexisting condition.\n\nShe studied at Smith College and the University of Wisconsin Law School and built a career as served on the Dane County Board, in the Wisconsin Assembly, and in the U.S. House, where she co-founded the Congressional LGBTQ+ Equality Caucus. She authored one of the first bills to allow generic biologic drugs.\n\nElected in 2012 as the nation's first openly gay senator, Baldwin champions Buy American rules, Great Lakes cleanup, and rural healthcare clinics.",
    ),
    Senator(
      id: "ron_johnson",
      name: "Ron Johnson",
      state: "Wisconsin",
      biography: "Ron Johnson was born in Mankato, Minnesota and moved to Wisconsin for college and worked nights to pay tuition, eventually helping his brother-in-law start the plastics company Pacur in Oshkosh.\n\nHe studied at the University of Minnesota and built a career as ran Pacur for decades, producing medical packaging and employing hundreds in the Fox Valley. He joined TEA Party rallies calling for lower taxes and simpler regulations.\n\nSince 2011 Johnson has focused on manufacturing supply chains, deficits, and investigations through the Homeland Security Committee.",
    ),
    Senator(
      id: "john_barrasso",
      name: "John Barrasso",
      state: "Wyoming",
      biography: "John Barrasso was born in Reading, Pennsylvania and moved west for medical school rotations and fell in love with Casper's open plains, eventually becoming known as 'Wyoming's doctor'.\n\nHe studied at Georgetown University and the Georgetown University School of Medicine and built a career as an orthopedic surgeon who served as president of the Wyoming Medical Society and a state senator before being appointed to the U.S. Senate in 2007. He hosted a long-running health tips segment on Wyoming television.\n\nBarrasso is now the Senate Republican Conference chair and advocates for energy independence, federal land access, and rural hospitals from Cheyenne to Cody.",
    ),
    Senator(
      id: "cynthia_lummis",
      name: "Cynthia Lummis",
      state: "Wyoming",
      biography: "Cynthia Lummis was born in Cheyenne, Wyoming and was elected to the state House at 24 and balanced legislative sessions with tending her family's cattle ranch.\n\nShe studied at the University of Wyoming for both animal science and law degrees and built a career as served as state treasurer, on the Wyoming Supreme Court's staff, and in the U.S. House from 2008 to 2016 before returning to ranching. She became an early advocate for digital asset regulation after investing personally in bitcoin.\n\nElected in 2020, Lummis pushes for responsible crypto frameworks, Powder River Basin jobs, and protection of the Wyoming Range.",
    ),
  ]
}
